//! Build-time module discovery — the "no core edits" mechanism.
//!
//! Scans the sibling `modules/` directory and generates `register_all`, a
//! function that constructs and registers every module crate. Adding a module
//! means dropping a crate under `modules/` (and its one dep line, which
//! `bin/new-module` appends to `Cargo.toml`); the registry regenerates on the
//! next build with no hand-edited central list — the AzerothCore module model,
//! in pure Cargo.
//!
//! Modules are emitted in sorted directory order so dispatch is deterministic,
//! which the anti-cheat re-simulation relies on.

use std::path::Path;
use std::{env, fs};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let out_dir = env::var("OUT_DIR").unwrap_or_default();
    let modules_dir = Path::new(&manifest_dir).join("../../modules");

    // Rebuild the registry whenever a module is added or removed.
    println!("cargo:rerun-if-changed={}", modules_dir.display());

    let mut idents = discover(&modules_dir);
    idents.sort();

    let calls: String = idents
        .iter()
        .map(|ident| format!("    host.register({ident}::module());\n"))
        .collect();
    let body = format!(
        "// @generated by crates/modules/build.rs — do not edit.\n\
         /// Register every module linked in under `modules/`, in sorted order.\n\
         fn register_all(host: &mut ::omm_module_api::ModuleHost) {{\n{calls}}}\n"
    );

    let out_path = Path::new(&out_dir).join("registrations.rs");
    if let Err(err) = fs::write(&out_path, body) {
        panic!("failed to write {}: {err}", out_path.display());
    }
}

/// The `extern`-crate identifier of every module under `dir`.
///
/// A module directory is any child holding a `Cargo.toml`; its crate identifier
/// follows the convention `omm_module_<dir with '-' as '_'>` (what
/// `bin/new-module` names the crate). We also emit `rerun-if-changed` per
/// `module.toml` so editing a manifest re-runs discovery.
fn discover(dir: &Path) -> Vec<String> {
    let Ok(entries) = fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut idents = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.join("Cargo.toml").is_file() {
            continue;
        }
        rerun_if_changed(&path.join("module.toml"));
        if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
            idents.push(format!("omm_module_{}", name.replace('-', "_")));
        }
    }
    idents
}

/// Emit a `rerun-if-changed` line for `path` if it exists.
fn rerun_if_changed(path: &Path) {
    if path.is_file() {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}
