import type { Catalog } from '@omm/i18n';

export const fr: Catalog = {
  common: {
    loading: 'Chargement…',
    retry: 'Réessayer',
    search: 'Rechercher',
    submit: 'Soumettre',
    cancel: 'Annuler',
    close: 'Fermer',
    empty: 'Rien à afficher encore.',
    gold: '{amount} or',
  },
  nav: {
    home: 'Accueil',
    play: 'Jouer',
    downloads: 'Téléchargements',
    armory: 'Armurerie',
    auction: 'Hôtel des ventes',
    feed: 'Flux du monde',
    login: 'Se connecter',
    register: 'Créer un compte',
    account: 'Compte',
    logout: 'Se déconnecter',
    skipToContent: 'Aller au contenu',
  },
  footer: {
    tagline: 'Un moteur MMORPG open-core. IP originale, sous licence MIT.',
    poweredBy: 'Propulsé par Open-MMORPG',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'Un royaume fonctionnant avec le moteur Open-MMORPG.',
    status: {
      heading: 'Statut du royaume',
      online: 'En ligne',
      offline: 'Hors ligne',
      population: '{count} / {capacity} aventuriers en ligne',
      loading: 'Vérification du royaume…',
      error: 'Statut du royaume non disponible',
    },
  },
  home: {
    heroCta: 'Entrer dans le royaume',
    downloadHeading: 'Télécharger le client',
    downloadBody: 'Jouez sur Windows, macOS ou Linux. Le client est une application native légère.',
    download: 'Télécharger',
    featuresHeading: 'Ce qui vous attend',
    feature: {
      worldTitle: 'Un monde vivant',
      worldBody: 'Autorisé par le serveur, dimensionné horizontalement, toujours vivant.',
      economyTitle: 'Une économie réelle',
      economyBody: 'Un hôtel des ventes transactionnel sans dupes, jamais.',
      armoryTitle: 'Votre légende, publique',
      armoryBody: 'Une armurerie de premier plan pour chaque personnage et guilde.',
    },
  },
  errors: {
    network: 'Impossible de joindre le royaume. Vérifiez votre connexion et réessayez.',
    validation:
      "Le royaume a envoyé quelque chose d'inattendu. C'est un bug — veuillez le signaler.",
    auth: 'Votre session a expiré. Veuillez vous reconnecter.',
    unknown: 'Un problème est survenu. Veuillez réessayer.',
  },
  notFound: {
    heading: 'Perdu dans les brumes',
    body: "Cette page n'existe pas dans ce royaume.",
    home: "Retourner à l'accueil",
  },
  auth: {
    login: {
      heading: 'Se connecter',
      email: 'E-mail',
      password: 'Mot de passe',
      submit: 'Se connecter',
      noAccount: 'Pas encore de compte ?',
      register: 'Créer un compte',
      success: 'Bon retour, {name}.',
    },
    register: {
      heading: 'Créer un compte',
      displayName: "Nom d'affichage",
      email: 'E-mail',
      password: 'Mot de passe',
      submit: 'Créer un compte',
      haveAccount: 'Vous avez déjà un compte ?',
      login: 'Se connecter',
      closed: "L'inscription est fermée dans ce royaume.",
      success: 'Compte créé. Bienvenue, {name}.',
    },
    error: {
      invalid_credentials: 'E-mail ou mot de passe incorrect.',
      registration_closed: "L'inscription est fermée dans ce royaume.",
      rate_limited: 'Trop de tentatives. Veuillez attendre et réessayer.',
      twofa_required: 'Entrez votre code à deux facteurs pour continuer.',
      email_taken: 'Cet e-mail est déjà enregistré.',
      wrong_password: 'Votre mot de passe actuel est incorrect.',
      password_too_short: 'Le mot de passe doit comporter au moins 8 caractères.',
      password_mismatch: 'Les nouveaux mots de passe ne correspondent pas.',
    },
    account: {
      heading: 'Compte',
      email: 'E-mail',
      displayName: "Nom d'affichage",
      memberSince: 'Membre depuis {date}',
      logout: 'Se déconnecter',
      loggedOut: 'Vous êtes déconnecté.',
      loginPrompt: 'Connectez-vous pour gérer votre compte.',
      settings: {
        heading: 'Paramètres du compte',
        profileHeading: 'Profil',
        saveProfile: 'Enregistrer le profil',
        profileSaved: 'Profil enregistré.',
        passwordHeading: 'Changer le mot de passe',
        currentPassword: 'Mot de passe actuel',
        newPassword: 'Nouveau mot de passe',
        confirmPassword: 'Confirmer le nouveau mot de passe',
        changePassword: 'Changer le mot de passe',
        passwordChanged: 'Mot de passe modifié.',
      },
    },
  },
  armory: {
    heading: 'Armurerie',
    searchLabel: 'Nom de personnage ou de guilde',
    searchPlaceholder: 'ex. Aria',
    searchCharacter: 'Rechercher un personnage',
    searchGuild: 'Rechercher une guilde',
    notFound: 'Aucun personnage ou guilde de ce nom dans ce royaume.',
    private: "Ce royaume garde l'armurerie privée.",
    character: {
      level: 'Niveau {level} {race} {class}',
      guild: 'Guilde',
      achievements: 'Succès',
      itemLevel: "Niveau d'objet {value}",
      itemLevelCol: 'Niv',
      gear: 'Équipement',
      slot: 'Emplacement',
      item: 'Objet',
      empty: 'Aucun équipement équipé.',
    },
    guild: {
      members: '{count} membres',
      roster: 'Effectif',
      member: 'Membre',
      rank: 'Rang',
      level: 'Niveau',
    },
  },
  auction: {
    heading: 'Hôtel des ventes',
    disabled: "L'hôtel des ventes est fermé dans ce royaume.",
    searchPlaceholder: 'Rechercher des objets…',
    col: {
      item: 'Objet',
      quantity: 'Qté',
      buyout: 'Achat immédiat',
      seller: 'Vendeur',
      time: 'Fin',
    },
    each: 'chacun',
    buy: 'Acheter',
    buying: 'Achat…',
    bought: '{item} acheté pour {price} or.',
    empty: 'Aucune annonce ne correspond à votre recherche.',
    priceHistory: 'Historique des prix (moyenne achat immédiat)',
  },
  feed: {
    heading: 'Flux du monde',
    disabled: 'Le flux du monde est désactivé dans ce royaume.',
    empty: 'Le monde est calme… pour le moment.',
    kind: {
      boss_kill: '{actor} a vaincu {target}.',
      world_boss_spawn: "{target} s'est réveillé dans {zone}.",
      faction_shift: '{actor} a pris le contrôle de {zone}.',
      bounty_posted: 'Une prime a été mise sur {target}.',
      milestone: '{target}',
      unknown: "Quelque chose s'agite dans le monde.",
    },
  },
  downloads: {
    heading: 'Téléchargements',
    body: 'Téléchargez le client de jeu pour votre plateforme. Vérifiez votre téléchargement avec les sommes de contrôle fournies.',
    installers: 'Installateurs',
    httpsNote: 'Tous les téléchargements sont servis via HTTPS avec chiffrement TLS.',
    version: 'Version',
    size: 'Taille',
    download: 'Télécharger',
    checksum: 'Somme de contrôle',
    requirements: 'Configuration requise',
    os: "Système d'exploitation",
    specs: 'Spécifications',
    verification: 'Vérifier votre téléchargement',
    verificationBody:
      "Après le téléchargement, vérifiez l'intégrité de l'installateur en utilisant la somme de contrôle ci-dessus.",
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: 'Comparez la sortie avec la somme de contrôle affichée ci-dessus.',
    backToHome: "Retour à l'accueil",
    verifier: {
      heading: 'Vérificateur de somme de contrôle',
      label: 'Entrez la somme de contrôle de votre fichier',
      placeholder: 'Collez la somme de contrôle SHA256 que vous avez calculée',
      verify: 'Vérifier',
      verifying: 'Vérification…',
      match: '✓ Correspondance — votre téléchargement est authentique',
      mismatch: '✗ Pas de correspondance — le fichier peut être corrompu',
      invalid: 'Format de somme de contrôle invalide (64 caractères hexadécimaux attendus)',
      morePlatforms: '+{count} plateformes supplémentaires',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'CPU Intel/AMD, 4 Go RAM, 500 Mo disque',
    osMacos: 'macOS 11+',
    specsMacos: 'CPU Intel/Apple, 4 Go RAM, 500 Mo disque',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'CPU x64, 4 Go RAM, 500 Mo disque',
  },
  cashShop: {
    heading: 'Boutique',
    allCategories: 'Toutes',
    buy: 'Acheter',
    buying: 'Achat…',
    bought: '{item} acheté pour {price} crédits.',
    currency: 'crédits',
    col: {
      item: 'Objet',
      category: 'Catégorie',
      price: 'Prix',
    },
    empty: 'Aucun objet dans cette catégorie.',
    category: {
      boosts: 'Améliorations',
      cosmetics: 'Cosmétiques',
      account: 'Compte',
      mounts: 'Montures',
    },
  },
};
