import type { Catalog } from '@omm/i18n';

export const pt: Catalog = {
  common: {
    loading: 'Carregando…',
    retry: 'Tentar novamente',
    search: 'Buscar',
    submit: 'Enviar',
    cancel: 'Cancelar',
    close: 'Fechar',
    empty: 'Nada para mostrar ainda.',
    gold: '{amount} ouro',
  },
  nav: {
    home: 'Início',
    play: 'Jogar',
    downloads: 'Downloads',
    armory: 'Arsenal',
    auction: 'Casa de leilões',
    feed: 'Feed do mundo',
    login: 'Entrar',
    register: 'Criar conta',
    account: 'Conta',
    logout: 'Sair',
    skipToContent: 'Pular para o conteúdo',
  },
  footer: {
    tagline: 'Um motor MMORPG de núcleo aberto. IP original, licenciado pelo MIT.',
    poweredBy: 'Desenvolvido com Open-MMORPG',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'Um reino executando no motor Open-MMORPG.',
    status: {
      heading: 'Status do reino',
      online: 'Online',
      offline: 'Offline',
      population: '{count} / {capacity} aventureiros online',
      loading: 'Verificando reino…',
      error: 'Status do reino indisponível',
    },
  },
  home: {
    heroCta: 'Entrar no reino',
    downloadHeading: 'Baixar o cliente',
    downloadBody: 'Jogue no Windows, macOS ou Linux. O cliente é um aplicativo nativo leve.',
    download: 'Baixar',
    featuresHeading: 'O que te espera',
    feature: {
      worldTitle: 'Um mundo vivo',
      worldBody: 'Autoritário pelo servidor, escalado horizontalmente, sempre vivo.',
      economyTitle: 'Uma economia real',
      economyBody: 'Uma casa de leilões transacional sem duplicatas, nunca.',
      armoryTitle: 'Sua lenda, pública',
      armoryBody: 'Um arsenal de primeira classe para cada personagem e guilda.',
    },
  },
  errors: {
    network: 'Não é possível alcançar o reino. Verifique sua conexão e tente novamente.',
    validation: 'O reino enviou algo inesperado. Isso é um bug — por favor, relate-o.',
    auth: 'Sua sessão expirou. Por favor, entre novamente.',
    unknown: 'Algo deu errado. Por favor, tente novamente.',
  },
  notFound: {
    heading: 'Perdido nas brumas',
    body: 'Esta página não existe neste reino.',
    home: 'Voltar ao início',
  },
  auth: {
    login: {
      heading: 'Entrar',
      email: 'E-mail',
      password: 'Senha',
      submit: 'Entrar',
      noAccount: 'Ainda não tem conta?',
      register: 'Criar uma',
      success: 'Bem-vindo de volta, {name}.',
    },
    register: {
      heading: 'Criar conta',
      displayName: 'Nome de exibição',
      email: 'E-mail',
      password: 'Senha',
      submit: 'Criar conta',
      haveAccount: 'Já tem conta?',
      login: 'Entrar',
      closed: 'O registro está fechado neste reino.',
      success: 'Conta criada. Bem-vindo, {name}.',
    },
    error: {
      invalid_credentials: 'E-mail ou senha incorretos.',
      registration_closed: 'O registro está fechado neste reino.',
      rate_limited: 'Muitas tentativas. Por favor, aguarde e tente novamente.',
      twofa_required: 'Digite seu código de dois fatores para continuar.',
      email_taken: 'Este e-mail já está registrado.',
    },
    account: {
      heading: 'Conta',
      email: 'E-mail',
      displayName: 'Nome de exibição',
      memberSince: 'Membro desde {date}',
      logout: 'Sair',
      loggedOut: 'Você saiu.',
      loginPrompt: 'Entre para gerenciar sua conta.',
    },
  },
  armory: {
    heading: 'Arsenal',
    searchLabel: 'Nome de personagem ou guilda',
    searchPlaceholder: 'ex. Aria',
    searchCharacter: 'Encontrar personagem',
    searchGuild: 'Encontrar guilda',
    notFound: 'Nenhum personagem ou guilda assim neste reino.',
    private: 'Este reino mantém o arsenal privado.',
    character: {
      level: 'Nível {level} {race} {class}',
      guild: 'Guilda',
      achievements: 'Conquistas',
      itemLevel: 'Nível de item {value}',
      itemLevelCol: 'Nv',
      gear: 'Equipamento',
      slot: 'Espaço',
      item: 'Item',
      empty: 'Nenhum equipamento equipado.',
    },
    guild: {
      members: '{count} membros',
      roster: 'Lista',
      member: 'Membro',
      rank: 'Patente',
      level: 'Nível',
    },
  },
  auction: {
    heading: 'Casa de leilões',
    disabled: 'A casa de leilões está fechada neste reino.',
    searchPlaceholder: 'Buscar itens…',
    col: { item: 'Item', quantity: 'Qtd', buyout: 'Compra', seller: 'Vendedor', time: 'Término' },
    each: 'cada',
    buy: 'Comprar',
    buying: 'Comprando…',
    bought: '{item} comprado por {price} ouro.',
    empty: 'Nenhuma listagem corresponde à sua busca.',
    priceHistory: 'Histórico de preços (média de compra)',
  },
  feed: {
    heading: 'Feed do mundo',
    disabled: 'O feed do mundo está desligado neste reino.',
    empty: 'O mundo está quieto… por enquanto.',
    kind: {
      boss_kill: '{actor} derrotou {target}.',
      world_boss_spawn: '{target} despertou em {zone}.',
      faction_shift: '{actor} assumiu o controle de {zone}.',
      bounty_posted: 'Uma recompensa foi postada em {target}.',
      milestone: '{target}',
      unknown: 'Algo se agita no mundo.',
    },
  },
  downloads: {
    heading: 'Downloads',
    body: 'Baixe o cliente do jogo para sua plataforma. Verifique seu download com os checksums fornecidos.',
    installers: 'Instaladores',
    httpsNote: 'Todos os downloads são servidos via HTTPS com criptografia TLS.',
    version: 'Versão',
    size: 'Tamanho',
    download: 'Baixar',
    checksum: 'Checksum',
    requirements: 'Requisitos do sistema',
    os: 'Sistema operacional',
    specs: 'Especificações',
    verification: 'Verificar seu download',
    verificationBody:
      'Após o download, verifique a integridade do instalador usando o checksum acima.',
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: 'Compare a saída com o checksum mostrado acima.',
    backToHome: 'Voltar ao início',
    verifier: {
      heading: 'Verificador de checksum',
      label: 'Digite o checksum do seu arquivo',
      placeholder: 'Cole o checksum SHA256 que você calculou',
      verify: 'Verificar',
      verifying: 'Verificando…',
      match: '✓ Combinação — seu download é autêntico',
      mismatch: '✗ Sem combinação — o arquivo pode estar corrompido',
      invalid: 'Formato de checksum inválido (esperados 64 caracteres hexadecimais)',
      morePlatforms: '+{count} mais plataformas',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'CPU Intel/AMD, 4GB RAM, 500MB disco',
    osMacos: 'macOS 11+',
    specsMacos: 'CPU Intel/Apple, 4GB RAM, 500MB disco',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'CPU x64, 4GB RAM, 500MB disco',
  },
  cashShop: {
    heading: 'Loja',
    allCategories: 'Todas',
    buy: 'Comprar',
    buying: 'Comprando…',
    bought: '{item} comprado por {price} créditos.',
    currency: 'créditos',
    col: { item: 'Item', category: 'Categoria', price: 'Preço' },
    empty: 'Nenhum item nesta categoria.',
    category: { boosts: 'Boosts', cosmetics: 'Cosméticos', account: 'Conta', mounts: 'Montarias' },
  },
};
