import type { Catalog } from '@omm/i18n';

export const ko: Catalog = {
  common: {
    loading: '로드 중…',
    retry: '재시도',
    search: '검색',
    submit: '제출',
    cancel: '취소',
    close: '닫기',
    empty: '아직 표시할 것이 없습니다.',
    gold: '{amount} 골드',
  },
  nav: {
    home: '홈',
    play: '플레이',
    downloads: '다운로드',
    armory: '무기고',
    auction: '경매장',
    feed: '월드 피드',
    login: '로그인',
    register: '계정 만들기',
    account: '계정',
    logout: '로그아웃',
    skipToContent: '콘텐츠로 건너뛰기',
  },
  footer: {
    tagline: '오픈 코어 MMORPG 엔진. 원작 IP, MIT 라이선스.',
    poweredBy: 'Open-MMORPG 구동',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'Open-MMORPG 엔진으로 실행되는 영역.',
    status: {
      heading: '영역 상태',
      online: '온라인',
      offline: '오프라인',
      population: '{count} / {capacity} 모험자 온라인',
      loading: '영역 확인 중…',
      error: '영역 상태를 사용할 수 없습니다',
    },
  },
  home: {
    heroCta: '영역 입장',
    downloadHeading: '클라이언트 다운로드',
    downloadBody:
      'Windows, macOS 또는 Linux에서 플레이하세요. 클라이언트는 가벼운 네이티브 앱입니다.',
    download: '다운로드',
    featuresHeading: '당신을 기다리는 것',
    feature: {
      worldTitle: '살아있는 세계',
      worldBody: '서버 권위, 수평 확장, 항상 활성.',
      economyTitle: '진정한 경제',
      economyBody: '트랜잭션 경매장, 복제 없음, 영원히.',
      armoryTitle: '당신의 전설, 공개',
      armoryBody: '모든 캐릭터와 길드를 위한 일급 무기고.',
    },
  },
  errors: {
    network: '영역에 연결할 수 없습니다. 연결을 확인하고 다시 시도하세요.',
    validation: '영역이 예기치 않은 것을 보냈습니다. 이것은 버그입니다 — 보고해주세요.',
    auth: '세션이 만료되었습니다. 다시 로그인하세요.',
    unknown: '문제가 발생했습니다. 다시 시도하세요.',
  },
  notFound: {
    heading: '안개 속에서 길을 잃음',
    body: '이 페이지는 이 영역에 존재하지 않습니다.',
    home: '홈으로 돌아가기',
  },
  auth: {
    login: {
      heading: '로그인',
      email: '이메일',
      password: '비밀번호',
      submit: '로그인',
      noAccount: '계정이 없으신가요?',
      register: '계정 만들기',
      success: '다시 오신 것을 환영합니다, {name}.',
    },
    register: {
      heading: '계정 만들기',
      displayName: '표시 이름',
      email: '이메일',
      password: '비밀번호',
      submit: '계정 만들기',
      haveAccount: '이미 계정이 있으신가요?',
      login: '로그인',
      closed: '이 영역에서는 등록이 닫혀 있습니다.',
      success: '계정이 생성되었습니다. 환영합니다, {name}.',
    },
    error: {
      invalid_credentials: '이메일 또는 비밀번호가 올바르지 않습니다.',
      registration_closed: '이 영역에서는 등록이 닫혀 있습니다.',
      rate_limited: '너무 많은 시도입니다. 잠시 기다린 후 다시 시도하세요.',
      twofa_required: '계속하려면 2단계 인증 코드를 입력하세요.',
      email_taken: '이 이메일은 이미 등록되어 있습니다.',
      wrong_password: '현재 비밀번호가 올바르지 않습니다.',
      password_too_short: '비밀번호는 최소 8자 이상이어야 합니다.',
      password_mismatch: '새 비밀번호가 일치하지 않습니다.',
    },
    account: {
      heading: '계정',
      email: '이메일',
      displayName: '표시 이름',
      memberSince: '{date}부터 회원',
      logout: '로그아웃',
      loggedOut: '로그아웃되었습니다.',
      loginPrompt: '계정을 관리하려면 로그인하세요.',
      settings: {
        heading: '계정 설정',
        profileHeading: '프로필',
        saveProfile: '프로필 저장',
        profileSaved: '프로필이 저장되었습니다.',
        passwordHeading: '비밀번호 변경',
        currentPassword: '현재 비밀번호',
        newPassword: '새 비밀번호',
        confirmPassword: '새 비밀번호 확인',
        changePassword: '비밀번호 변경',
        passwordChanged: '비밀번호가 변경되었습니다.',
      },
    },
  },
  armory: {
    heading: '무기고',
    searchLabel: '캐릭터 또는 길드 이름',
    searchPlaceholder: '예: Aria',
    searchCharacter: '캐릭터 찾기',
    searchGuild: '길드 찾기',
    notFound: '이 영역에 그런 캐릭터나 길드가 없습니다.',
    private: '이 영역은 무기고를 비공개로 유지합니다.',
    character: {
      level: '레벨 {level} {race} {class}',
      guild: '길드',
      achievements: '성취',
      itemLevel: '아이템 레벨 {value}',
      itemLevelCol: '템레',
      gear: '장비',
      slot: '슬롯',
      item: '아이템',
      empty: '장착한 장비가 없습니다.',
    },
    guild: {
      members: '{count} 명의 회원',
      roster: '명단',
      member: '회원',
      rank: '순위',
      level: '레벨',
    },
  },
  auction: {
    heading: '경매장',
    disabled: '이 영역에서 경매장이 닫혀 있습니다.',
    searchPlaceholder: '아이템 검색…',
    col: { item: '아이템', quantity: '수량', buyout: '즉시구매가', seller: '판매자', time: '종료' },
    each: '개당',
    buy: '구매',
    buying: '구매 중…',
    bought: '{item}을(를) {price} 골드에 구매했습니다.',
    empty: '검색과 일치하는 경매가 없습니다.',
    priceHistory: '가격 기록 (평균 즉시구매가)',
  },
  feed: {
    heading: '월드 피드',
    disabled: '이 영역에서 월드 피드가 꺼져 있습니다.',
    empty: '세상은 조용합니다… 당분간.',
    kind: {
      boss_kill: '{actor}이(가) {target}을(를) 물리쳤습니다.',
      world_boss_spawn: '{target}이(가) {zone}에서 깨어났습니다.',
      faction_shift: '{actor}이(가) {zone}의 통제권을 장악했습니다.',
      bounty_posted: '{target}에 현상금이 걸렸습니다.',
      milestone: '{target}',
      unknown: '세상에 무언가 일어나고 있습니다.',
    },
  },
  downloads: {
    heading: '다운로드',
    body: '플랫폼용 게임 클라이언트를 다운로드하세요. 제공된 체크섬으로 다운로드를 확인하세요.',
    installers: '설치 프로그램',
    httpsNote: '모든 다운로드는 TLS 암호화가 있는 HTTPS를 통해 제공됩니다.',
    version: '버전',
    size: '크기',
    download: '다운로드',
    checksum: '체크섬',
    requirements: '시스템 요구사항',
    os: '운영 체제',
    specs: '사양',
    verification: '다운로드 확인',
    verificationBody: '다운로드 후 위의 체크섬을 사용하여 설치 프로그램의 무결성을 확인하세요.',
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: '출력을 위에 표시된 체크섬과 비교하세요.',
    backToHome: '홈으로 돌아가기',
    verifier: {
      heading: '체크섬 검증기',
      label: '파일의 체크섬 입력',
      placeholder: '계산한 SHA256 체크섬을 붙여넣으세요',
      verify: '확인',
      verifying: '확인 중…',
      match: '✓ 일치 — 다운로드가 정품입니다',
      mismatch: '✗ 불일치 — 파일이 손상되었을 수 있습니다',
      invalid: '잘못된 체크섬 형식 (64자 16진수 문자 필요)',
      morePlatforms: '+{count}개 더 많은 플랫폼',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'Intel/AMD CPU, 4GB RAM, 500MB 디스크',
    osMacos: 'macOS 11+',
    specsMacos: 'Intel/Apple CPU, 4GB RAM, 500MB 디스크',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'x64 CPU, 4GB RAM, 500MB 디스크',
  },
  cashShop: {
    heading: '캐시 샵',
    allCategories: '전체',
    buy: '구매',
    buying: '구매 중…',
    bought: '{item}을(를) {price} 크레딧에 구매했습니다.',
    currency: '크레딧',
    col: {
      item: '아이템',
      category: '카테고리',
      price: '가격',
    },
    empty: '이 카테고리에 아이템이 없습니다.',
    category: {
      boosts: '강화',
      cosmetics: '미용품',
      account: '계정',
      mounts: '탈것',
    },
  },
};
