import type { Catalog } from '@omm/i18n';

/**
 * Spanish catalog — the single source of copy, authored nested by feature.
 * Every user-facing string in the app lives here; components call `t()`,
 * never a bare literal. A missing key renders `⟦key⟧` (loud, never silent).
 * Operators add a language by dropping a sibling catalog (e.g. `es`), no code
 * change. → docs/specs/web-client/i18n
 */
export const es: Catalog = {
  common: {
    loading: 'Cargando…',
    retry: 'Reintentar',
    search: 'Buscar',
    submit: 'Enviar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    empty: 'Aún nada que mostrar.',
    gold: '{amount} oro',
  },
  nav: {
    home: 'Inicio',
    play: 'Jugar',
    downloads: 'Descargas',
    armory: 'Arsenal',
    auction: 'Casa de subastas',
    feed: 'Feed del mundo',
    login: 'Iniciar sesión',
    register: 'Crear cuenta',
    account: 'Cuenta',
    logout: 'Cerrar sesión',
    skipToContent: 'Saltar al contenido',
  },
  footer: {
    tagline: 'Un motor MMORPG de código abierto. IP original, licenciado bajo MIT.',
    poweredBy: 'Funciona con Open-MMORPG',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'Un reino que funciona con el motor Open-MMORPG.',
    status: {
      heading: 'Estado del reino',
      online: 'En línea',
      offline: 'Fuera de línea',
      population: '{count} / {capacity} aventureros en línea',
      loading: 'Verificando reino…',
      error: 'Estado del reino no disponible',
    },
  },
  home: {
    heroCta: 'Entra al reino',
    downloadHeading: 'Descargar el cliente',
    downloadBody: 'Juega en Windows, macOS o Linux. El cliente es una aplicación nativa ligera.',
    download: 'Descargar',
    featuresHeading: 'Te espera',
    feature: {
      worldTitle: 'Un mundo vivo',
      worldBody: 'Autorizado por el servidor, escalado horizontalmente, siempre vivo.',
      economyTitle: 'Una economía real',
      economyBody: 'Una casa de subastas transaccional sin duplicados, nunca.',
      armoryTitle: 'Tu leyenda, pública',
      armoryBody: 'Un arsenal de primera clase para cada personaje y guild.',
    },
  },
  errors: {
    network: 'No se puede alcanzar el reino. Verifica tu conexión y vuelve a intentar.',
    validation: 'El reino envió algo inesperado. Esto es un error — por favor repórtalo.',
    auth: 'Tu sesión ha expirado. Por favor inicia sesión nuevamente.',
    unknown: 'Algo salió mal. Por favor intenta de nuevo.',
  },
  notFound: {
    heading: 'Perdido en las brumas',
    body: 'Esta página no existe en este reino.',
    home: 'Volver al inicio',
  },
  auth: {
    login: {
      heading: 'Iniciar sesión',
      email: 'Correo electrónico',
      password: 'Contraseña',
      submit: 'Iniciar sesión',
      noAccount: '¿Aún no tienes cuenta?',
      register: 'Crear una',
      success: 'Bienvenido de vuelta, {name}.',
    },
    register: {
      heading: 'Crear cuenta',
      displayName: 'Nombre para mostrar',
      email: 'Correo electrónico',
      password: 'Contraseña',
      submit: 'Crear cuenta',
      haveAccount: '¿Ya tienes cuenta?',
      login: 'Iniciar sesión',
      closed: 'El registro está cerrado en este reino.',
      success: 'Cuenta creada. Bienvenido, {name}.',
    },
    error: {
      invalid_credentials: 'El correo electrónico o la contraseña son incorrectos.',
      registration_closed: 'El registro está cerrado en este reino.',
      rate_limited: 'Demasiados intentos. Por favor espera e intenta de nuevo.',
      twofa_required: 'Ingresa tu código de dos factores para continuar.',
      email_taken: 'Este correo electrónico ya está registrado.',
      wrong_password: 'Tu contraseña actual es incorrecta.',
      password_too_short: 'La contraseña debe tener al menos 8 caracteres.',
      password_mismatch: 'Las nuevas contraseñas no coinciden.',
    },
    account: {
      heading: 'Cuenta',
      email: 'Correo electrónico',
      displayName: 'Nombre para mostrar',
      memberSince: 'Miembro desde {date}',
      logout: 'Cerrar sesión',
      loggedOut: 'Has cerrado sesión.',
      loginPrompt: 'Inicia sesión para administrar tu cuenta.',
      settings: {
        heading: 'Ajustes de la cuenta',
        profileHeading: 'Perfil',
        saveProfile: 'Guardar perfil',
        profileSaved: 'Perfil guardado.',
        passwordHeading: 'Cambiar contraseña',
        currentPassword: 'Contraseña actual',
        newPassword: 'Nueva contraseña',
        confirmPassword: 'Confirmar nueva contraseña',
        changePassword: 'Cambiar contraseña',
        passwordChanged: 'Contraseña cambiada.',
      },
    },
  },
  armory: {
    heading: 'Arsenal',
    searchLabel: 'Nombre de personaje o guild',
    searchPlaceholder: 'ej. Aria',
    searchCharacter: 'Buscar personaje',
    searchGuild: 'Buscar guild',
    notFound: 'No existe tal personaje o guild en este reino.',
    private: 'Este reino mantiene el arsenal privado.',
    character: {
      level: 'Nivel {level} {race} {class}',
      guild: 'Guild',
      achievements: 'Logros',
      itemLevel: 'Nivel de objeto {value}',
      itemLevelCol: 'NO',
      gear: 'Equipo',
      slot: 'Espacio',
      item: 'Objeto',
      empty: 'Sin equipo equipado.',
    },
    guild: {
      members: '{count} miembros',
      roster: 'Lista de miembros',
      member: 'Miembro',
      rank: 'Rango',
      level: 'Nivel',
    },
  },
  auction: {
    heading: 'Casa de subastas',
    disabled: 'La casa de subastas está cerrada en este reino.',
    searchPlaceholder: 'Buscar objetos…',
    col: {
      item: 'Objeto',
      quantity: 'Cant.',
      buyout: 'Compra directa',
      seller: 'Vendedor',
      time: 'Termina',
    },
    each: 'c/u',
    buy: 'Comprar',
    buying: 'Comprando…',
    bought: '{item} comprado por {price} oro.',
    empty: 'No hay listados que coincidan con tu búsqueda.',
    priceHistory: 'Historial de precios (promedio de compra directa)',
  },
  feed: {
    heading: 'Feed del mundo',
    disabled: 'El feed del mundo está desactivado en este reino.',
    empty: 'El mundo está tranquilo… por ahora.',
    kind: {
      boss_kill: '{actor} derrotó a {target}.',
      world_boss_spawn: '{target} ha despertado en {zone}.',
      faction_shift: '{actor} tomó el control de {zone}.',
      bounty_posted: 'Se publicó una recompensa sobre {target}.',
      milestone: '{target}',
      unknown: 'Algo se agita en el mundo.',
    },
  },
  downloads: {
    heading: 'Descargas',
    body: 'Descarga el cliente del juego para tu plataforma. Verifica tu descarga con las checksums proporcionadas.',
    installers: 'Instaladores',
    httpsNote: 'Todas las descargas se sirven a través de HTTPS con encriptación TLS.',
    version: 'Versión',
    size: 'Tamaño',
    download: 'Descargar',
    checksum: 'Checksum',
    requirements: 'Requisitos del sistema',
    os: 'Sistema operativo',
    specs: 'Especificaciones',
    verification: 'Verificar tu descarga',
    verificationBody:
      'Después de descargar, verifica la integridad del instalador usando la checksum de arriba.',
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: 'Compara la salida con la checksum mostrada arriba.',
    backToHome: 'Volver al inicio',
    verifier: {
      heading: 'Verificador de checksum',
      label: 'Ingresa la checksum de tu archivo',
      placeholder: 'Pega la checksum SHA256 que calculaste',
      verify: 'Verificar',
      verifying: 'Verificando…',
      match: '✓ Coincide — tu descarga es auténtica',
      mismatch: '✗ Sin coincidencia — el archivo podría estar dañado',
      invalid: 'Formato de checksum inválido (se esperaban 64 caracteres hexadecimales)',
      morePlatforms: '+{count} plataformas más',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'CPU Intel/AMD, 4 GB RAM, 500 MB disco',
    osMacos: 'macOS 11+',
    specsMacos: 'CPU Intel/Apple, 4 GB RAM, 500 MB disco',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'CPU x64, 4 GB RAM, 500 MB disco',
  },
  cashShop: {
    heading: 'Tienda',
    allCategories: 'Todas',
    buy: 'Comprar',
    buying: 'Comprando…',
    bought: '{item} comprado por {price} créditos.',
    currency: 'créditos',
    col: {
      item: 'Objeto',
      category: 'Categoría',
      price: 'Precio',
    },
    empty: 'No hay objetos en esta categoría.',
    category: {
      boosts: 'Mejoras',
      cosmetics: 'Cosméticos',
      account: 'Cuenta',
      mounts: 'Monturas',
    },
  },
};
