import type { Catalog } from '@omm/i18n';

export const ja: Catalog = {
  common: {
    loading: '読み込み中…',
    retry: '再試行',
    search: '検索',
    submit: '送信',
    cancel: 'キャンセル',
    close: '閉じる',
    empty: 'まだ表示するものがありません。',
    gold: '{amount}ゴールド',
  },
  nav: {
    home: 'ホーム',
    play: 'プレイ',
    downloads: 'ダウンロード',
    armory: '武器庫',
    auction: 'オークションハウス',
    feed: 'ワールドフィード',
    login: 'ログイン',
    register: 'アカウント作成',
    account: 'アカウント',
    logout: 'ログアウト',
    skipToContent: 'コンテンツへスキップ',
  },
  footer: {
    tagline: 'オープンコアMMORPGエンジン。オリジナルIP、MITライセンス。',
    poweredBy: 'Open-MMORPG搭載',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'Open-MMORPGエンジンで動作するレルム。',
    status: {
      heading: 'レルムステータス',
      online: 'オンライン',
      offline: 'オフライン',
      population: '{count} / {capacity}人の冒険者がオンライン',
      loading: 'レルム確認中…',
      error: 'レルムステータスを利用できません',
    },
  },
  home: {
    heroCta: 'レルムに入る',
    downloadHeading: 'クライアントをダウンロード',
    downloadBody: 'Windows、macOS、またはLinuxでプレイ。クライアントは軽量なネイティブアプリです。',
    download: 'ダウンロード',
    featuresHeading: 'あなたを待つもの',
    feature: {
      worldTitle: '生きている世界',
      worldBody: 'サーバー主導、水平スケーリング、常に稼働中。',
      economyTitle: '本物の経済',
      economyBody: 'トランザクションオークションハウス、重複なし、永遠に。',
      armoryTitle: 'あなたの伝説、公開',
      armoryBody: 'すべてのキャラクターとギルドのための第一級武器庫。',
    },
  },
  errors: {
    network: 'レルムに接続できません。接続を確認して再試行してください。',
    validation: 'レルムが予期しないものを送信しました。これはバグです — 報告してください。',
    auth: 'セッションが期限切れになりました。再度ログインしてください。',
    unknown: 'エラーが発生しました。もう一度お試しください。',
  },
  notFound: {
    heading: '霧の中で迷子',
    body: 'このページはこのレルムには存在しません。',
    home: 'ホームに戻る',
  },
  auth: {
    login: {
      heading: 'ログイン',
      email: 'メールアドレス',
      password: 'パスワード',
      submit: 'ログイン',
      noAccount: 'まだアカウントをお持ちではありませんか？',
      register: 'アカウントを作成',
      success: 'おかえりなさい、{name}。',
    },
    register: {
      heading: 'アカウント作成',
      displayName: '表示名',
      email: 'メールアドレス',
      password: 'パスワード',
      submit: 'アカウント作成',
      haveAccount: 'すでにアカウントをお持ちですか？',
      login: 'ログイン',
      closed: 'このレルムでは登録が閉じています。',
      success: 'アカウントを作成しました。ようこそ、{name}。',
    },
    error: {
      invalid_credentials: 'メールアドレスまたはパスワードが正しくありません。',
      registration_closed: 'このレルムでは登録が閉じています。',
      rate_limited: '試行回数が多すぎます。お待ちいただいてから再試行してください。',
      twofa_required: '続行するには2要素認証コードを入力してください。',
      email_taken: 'このメールアドレスはすでに登録されています。',
    },
    account: {
      heading: 'アカウント',
      email: 'メールアドレス',
      displayName: '表示名',
      memberSince: '{date}からメンバー',
      logout: 'ログアウト',
      loggedOut: 'ログアウトしました。',
      loginPrompt: 'アカウントを管理するにはログインしてください。',
    },
  },
  armory: {
    heading: '武器庫',
    searchLabel: 'キャラクターまたはギルド名',
    searchPlaceholder: '例. Aria',
    searchCharacter: 'キャラクターを検索',
    searchGuild: 'ギルドを検索',
    notFound: 'このレルムにそのようなキャラクターまたはギルドはいません。',
    private: 'このレルムは武器庫を非公開にしています。',
    character: {
      level: 'レベル{level} {race} {class}',
      guild: 'ギルド',
      achievements: '実績',
      itemLevel: 'アイテムレベル{value}',
      itemLevelCol: 'IL',
      gear: '装備',
      slot: 'スロット',
      item: 'アイテム',
      empty: '装備なし。',
    },
    guild: {
      members: '{count}人のメンバー',
      roster: '名簿',
      member: 'メンバー',
      rank: 'ランク',
      level: 'レベル',
    },
  },
  auction: {
    heading: 'オークションハウス',
    disabled: 'このレルムではオークションハウスが閉じています。',
    searchPlaceholder: 'アイテムを検索…',
    col: { item: 'アイテム', quantity: '数量', buyout: '即落価格', seller: '出品者', time: '終了' },
    each: '個',
    buy: '購入',
    buying: '購入中…',
    bought: '{item}を{price}ゴールドで購入しました。',
    empty: '検索条件に一致する出品がありません。',
    priceHistory: '価格履歴（平均即落価格）',
  },
  feed: {
    heading: 'ワールドフィード',
    disabled: 'このレルムではワールドフィードがオフになっています。',
    empty: '世界は静か… 今のところ。',
    kind: {
      boss_kill: '{actor}が{target}を倒しました。',
      world_boss_spawn: '{target}が{zone}で目覚めました。',
      faction_shift: '{actor}が{zone}の支配権を掌握しました。',
      bounty_posted: '{target}に賞金がかけられました。',
      milestone: '{target}',
      unknown: '世界で何かが起こっています。',
    },
  },
  downloads: {
    heading: 'ダウンロード',
    body: 'プラットフォーム用のゲームクライアントをダウンロードしてください。提供されたチェックサムでダウンロードを確認してください。',
    installers: 'インストーラー',
    httpsNote: 'すべてのダウンロードはTLS暗号化付きHTTPSで提供されます。',
    version: 'バージョン',
    size: 'サイズ',
    download: 'ダウンロード',
    checksum: 'チェックサム',
    requirements: 'システム要件',
    os: 'オペレーティングシステム',
    specs: '仕様',
    verification: 'ダウンロードを確認',
    verificationBody:
      'ダウンロード後、上記のチェックサムを使用してインストーラーの整合性を確認してください。',
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: '出力を上記のチェックサムと比較してください。',
    backToHome: 'ホームに戻る',
    verifier: {
      heading: 'チェックサム検証ツール',
      label: 'ファイルのチェックサムを入力',
      placeholder: '計算したSHA256チェックサムを貼り付けてください',
      verify: '確認',
      verifying: '確認中…',
      match: '✓ 一致 — ダウンロードは本物です',
      mismatch: '✗ 不一致 — ファイルが破損している可能性があります',
      invalid: '無効なチェックサム形式（64文字の16進数が必要です）',
      morePlatforms: '+{count}プラットフォーム追加',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'Intel/AMD CPU、4GB RAM、500MBディスク',
    osMacos: 'macOS 11+',
    specsMacos: 'Intel/Apple CPU、4GB RAM、500MBディスク',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'x64 CPU、4GB RAM、500MBディスク',
  },
  cashShop: {
    heading: 'キャッシュショップ',
    allCategories: 'すべて',
    buy: '購入',
    buying: '購入中…',
    bought: '{item}を{price}クレジットで購入しました。',
    currency: 'クレジット',
    col: {
      item: 'アイテム',
      category: 'カテゴリー',
      price: '価格',
    },
    empty: 'このカテゴリーにアイテムがありません。',
    category: {
      boosts: 'ブースト',
      cosmetics: 'コスメ',
      account: 'アカウント',
      mounts: 'マウント',
    },
  },
};
