import type { Catalog } from '@omm/i18n';

/**
 * German catalog — the single source of copy, authored nested by feature.
 * Every user-facing string in the app lives here; components call `t()`,
 * never a bare literal. A missing key renders `⟦key⟧` (loud, never silent).
 * Operators add a language by dropping a sibling catalog (e.g. `de`), no code
 * change. → docs/specs/web-client/i18n
 */
export const de: Catalog = {
  common: {
    loading: 'Laden…',
    retry: 'Wiederholen',
    search: 'Suchen',
    submit: 'Absenden',
    cancel: 'Abbrechen',
    close: 'Schließen',
    empty: 'Noch nichts zu sehen.',
    gold: '{amount} Gold',
  },
  nav: {
    home: 'Startseite',
    play: 'Spielen',
    downloads: 'Downloads',
    armory: 'Rüstungskammer',
    auction: 'Auktionshaus',
    feed: 'Welt-Feed',
    login: 'Anmelden',
    register: 'Konto erstellen',
    account: 'Konto',
    logout: 'Abmelden',
    skipToContent: 'Zum Inhalt springen',
  },
  footer: {
    tagline: 'Eine Open-Core-MMORPG-Engine. Original-IP, MIT-lizenziert.',
    poweredBy: 'Betrieben mit Open-MMORPG',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'Ein Reich, das auf der Open-MMORPG-Engine läuft.',
    status: {
      heading: 'Reichsstatus',
      online: 'Online',
      offline: 'Offline',
      population: '{count} / {capacity} Abenteurer online',
      loading: 'Reich wird überprüft…',
      error: 'Reichsstatus nicht verfügbar',
    },
  },
  home: {
    heroCta: 'Betrete das Reich',
    downloadHeading: 'Client herunterladen',
    downloadBody: 'Spiele unter Windows, macOS oder Linux. Der Client ist eine dünne native App.',
    download: 'Herunterladen',
    featuresHeading: 'Was dich erwartet',
    feature: {
      worldTitle: 'Eine lebendige Welt',
      worldBody: 'Server-autoritativ, horizontal skaliert, immer lebendig.',
      economyTitle: 'Eine echte Wirtschaft',
      economyBody: 'Ein transactionales Auktionshaus ohne Dupes, niemals.',
      armoryTitle: 'Deine Legende, öffentlich',
      armoryBody: 'Eine erstklassige Rüstungskammer für jeden Charakter und jede Gilde.',
    },
  },
  errors: {
    network:
      'Das Reich kann nicht erreicht werden. Überprüfe deine Verbindung und versuche es erneut.',
    validation: 'Das Reich hat etwas Unerwartetes gesendet. Das ist ein Bug — bitte melde ihn.',
    auth: 'Deine Sitzung ist abgelaufen. Bitte melde dich erneut an.',
    unknown: 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
  },
  notFound: {
    heading: 'In den Nebeln verloren',
    body: 'Diese Seite existiert in diesem Reich nicht.',
    home: 'Zurück zur Startseite',
  },
  auth: {
    login: {
      heading: 'Anmelden',
      email: 'E-Mail',
      password: 'Passwort',
      submit: 'Anmelden',
      noAccount: 'Noch kein Konto?',
      register: 'Konto erstellen',
      success: 'Willkommen zurück, {name}.',
    },
    register: {
      heading: 'Konto erstellen',
      displayName: 'Anzeigename',
      email: 'E-Mail',
      password: 'Passwort',
      submit: 'Konto erstellen',
      haveAccount: 'Du hast bereits ein Konto?',
      login: 'Anmelden',
      closed: 'Die Registrierung ist in diesem Reich geschlossen.',
      success: 'Konto erstellt. Willkommen, {name}.',
    },
    error: {
      invalid_credentials: 'E-Mail oder Passwort ist falsch.',
      registration_closed: 'Die Registrierung ist in diesem Reich geschlossen.',
      rate_limited: 'Zu viele Versuche. Bitte warte und versuche es erneut.',
      twofa_required: 'Gib deinen Zwei-Faktor-Code ein, um fortzufahren.',
      email_taken: 'Diese E-Mail ist bereits registriert.',
      wrong_password: 'Dein aktuelles Passwort ist falsch.',
      password_too_short: 'Das Passwort muss mindestens 8 Zeichen lang sein.',
      password_mismatch: 'Die neuen Passwörter stimmen nicht überein.',
    },
    account: {
      heading: 'Konto',
      email: 'E-Mail',
      displayName: 'Anzeigename',
      memberSince: 'Mitglied seit {date}',
      logout: 'Abmelden',
      loggedOut: 'Du bist abgemeldet.',
      loginPrompt: 'Melde dich an, um dein Konto zu verwalten.',
      settings: {
        heading: 'Kontoeinstellungen',
        profileHeading: 'Profil',
        saveProfile: 'Profil speichern',
        profileSaved: 'Profil gespeichert.',
        passwordHeading: 'Passwort ändern',
        currentPassword: 'Aktuelles Passwort',
        newPassword: 'Neues Passwort',
        confirmPassword: 'Neues Passwort bestätigen',
        changePassword: 'Passwort ändern',
        passwordChanged: 'Passwort geändert.',
      },
    },
  },
  armory: {
    heading: 'Rüstungskammer',
    searchLabel: 'Charakter- oder Gildenname',
    searchPlaceholder: 'z.B. Aria',
    searchCharacter: 'Charakter finden',
    searchGuild: 'Gilde finden',
    notFound: 'Kein solcher Charakter oder keine solche Gilde in diesem Reich.',
    private: 'Dieses Reich hält die Rüstungskammer privat.',
    character: {
      level: 'Stufe {level} {race} {class}',
      guild: 'Gilde',
      achievements: 'Erfolge',
      itemLevel: 'Gegenstandsstufe {value}',
      itemLevelCol: 'GS',
      gear: 'Ausrüstung',
      slot: 'Slot',
      item: 'Gegenstand',
      empty: 'Keine Ausrüstung angelegt.',
    },
    guild: {
      members: '{count} Mitglieder',
      roster: 'Mitgliederliste',
      member: 'Mitglied',
      rank: 'Rang',
      level: 'Stufe',
    },
  },
  auction: {
    heading: 'Auktionshaus',
    disabled: 'Das Auktionshaus ist in diesem Reich geschlossen.',
    searchPlaceholder: 'Gegenstände suchen…',
    col: {
      item: 'Gegenstand',
      quantity: 'Menge',
      buyout: 'Sofortkauf',
      seller: 'Verkäufer',
      time: 'Endet',
    },
    each: 'pro Stück',
    buy: 'Kaufen',
    buying: 'Kaufe…',
    bought: '{item} für {price} Gold gekauft.',
    empty: 'Keine Angebote passen zu deiner Suche.',
    priceHistory: 'Preisgeschichte (Durchschnitt Sofortkauf)',
  },
  feed: {
    heading: 'Welt-Feed',
    disabled: 'Der Welt-Feed ist in diesem Reich deaktiviert.',
    empty: 'Die Welt ist ruhig… vorerst.',
    kind: {
      boss_kill: '{actor} hat {target} besiegt.',
      world_boss_spawn: '{target} ist in {zone} erwacht.',
      faction_shift: '{actor} hat die Kontrolle über {zone} übernommen.',
      bounty_posted: 'Eine Kopfgeld wurde auf {target} gesetzt.',
      milestone: '{target}',
      unknown: 'Etwas regt sich in der Welt.',
    },
  },
  downloads: {
    heading: 'Downloads',
    body: 'Lade den Spiel-Client für deine Plattform herunter. Überprüfe deinen Download mit den bereitgestellten Checksums.',
    installers: 'Installationsprogramme',
    httpsNote: 'Alle Downloads werden über HTTPS mit TLS-Verschlüsselung bereitgestellt.',
    version: 'Version',
    size: 'Größe',
    download: 'Herunterladen',
    checksum: 'Checksumme',
    requirements: 'Systemanforderungen',
    os: 'Betriebssystem',
    specs: 'Spezifikationen',
    verification: 'Download überprüfen',
    verificationBody:
      'Überprüfe nach dem Download die Integrität des Installationsprogramms mit der Checksumme oben.',
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: 'Vergleiche die Ausgabe mit der oben angezeigten Checksumme.',
    backToHome: 'Zurück zur Startseite',
    verifier: {
      heading: 'Checksummen-Prüfer',
      label: 'Checksumme aus deiner Datei eingeben',
      placeholder: 'Füge die berechnete SHA256-Checksumme ein',
      verify: 'Überprüfen',
      verifying: 'Überprüfe…',
      match: '✓ Übereinstimmung — dein Download ist authentisch',
      mismatch: '✗ Keine Übereinstimmung — Datei könnte beschädigt sein',
      invalid: 'Ungültiges Checksummen-Format (64 Hex-Zeichen erwartet)',
      morePlatforms: '+{count} weitere Plattformen',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'Intel/AMD CPU, 4 GB RAM, 500 MB Festplatte',
    osMacos: 'macOS 11+',
    specsMacos: 'Intel/Apple CPU, 4 GB RAM, 500 MB Festplatte',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'x64 CPU, 4 GB RAM, 500 MB Festplatte',
  },
  cashShop: {
    heading: 'Cash Shop',
    allCategories: 'Alle',
    buy: 'Kaufen',
    buying: 'Kaufe…',
    bought: '{item} für {price} Credits gekauft.',
    currency: 'Credits',
    col: {
      item: 'Gegenstand',
      category: 'Kategorie',
      price: 'Preis',
    },
    empty: 'Keine Gegenstände in dieser Kategorie.',
    category: {
      boosts: 'Boosts',
      cosmetics: 'Kosmetika',
      account: 'Konto',
      mounts: 'Reittiere',
    },
  },
};
