import type { Catalog } from '@omm/i18n';

export const tr: Catalog = {
  common: {
    loading: 'Yükleniyor…',
    retry: 'Tekrar dene',
    search: 'Ara',
    submit: 'Gönder',
    cancel: 'İptal',
    close: 'Kapat',
    empty: 'Henüz gösterilecek bir şey yok.',
    gold: '{amount} altın',
  },
  nav: {
    home: 'Ana sayfa',
    play: 'Oyna',
    downloads: 'İndirilenler',
    armory: 'Cephanelik',
    auction: 'Auction evi',
    feed: 'Dünya akışı',
    login: 'Giriş yap',
    register: 'Hesap oluştur',
    account: 'Hesap',
    logout: 'Çıkış yap',
    skipToContent: 'İçeriğe atla',
  },
  footer: {
    tagline: 'Açık çekirdekli bir MMORPG motoru. Orijinal IP, MIT lisanslı.',
    poweredBy: 'Open-MMORPG ile desteklenmektedir',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'Open-MMORPG motoru üzerinde çalışan bir realm.',
    status: {
      heading: 'Realm durumu',
      online: 'Çevrimiçi',
      offline: 'Çevrimdışı',
      population: '{count} / {capacity} maceracı çevrimiçi',
      loading: 'Realm kontrol ediliyor…',
      error: 'Realm durumu kullanılamıyor',
    },
  },
  home: {
    heroCta: 'Realme gir',
    downloadHeading: 'İstemciyi indir',
    downloadBody: 'Windows, macOS veya Linux üzerinde oyna. İstemci, hafif bir yerel uygulamadır.',
    download: 'İndir',
    featuresHeading: 'Sizi neler bekliyor',
    feature: {
      worldTitle: 'Canlı bir dünya',
      worldBody: 'Sunucu otoriter, yatay ölçeklenebilir, her zaman canlı.',
      economyTitle: 'Gerçek bir ekonomi',
      economyBody: 'Hiçbir zaman kopya olmayan transactional bir auction evi.',
      armoryTitle: 'Efsaneniz, herkese açık',
      armoryBody: 'Her karakter ve lonca için birinci sınıf bir cephanelik.',
    },
  },
  errors: {
    network: 'Realme ulaşılamıyor. Bağlantınızı kontrol edin ve tekrar deneyin.',
    validation: 'Realm beklenmedik bir şey gönderdi. Bu bir hatadır — lütfen bildirin.',
    auth: 'Oturumunuz süresi doldu. Lütfen tekrar giriş yapın.',
    unknown: 'Bir şey yanlış gitti. Lütfen tekrar deneyin.',
  },
  notFound: {
    heading: 'Sislere kayboldunuz',
    body: 'Bu sayfa bu realmda mevcut değil.',
    home: 'Ana sayfaya dön',
  },
  auth: {
    login: {
      heading: 'Giriş yap',
      email: 'E-posta',
      password: 'Şifre',
      submit: 'Giriş yap',
      noAccount: 'Hesabınız yok mu?',
      register: 'Hesap oluşturun',
      success: 'Tekrar hoş geldiniz, {name}.',
    },
    register: {
      heading: 'Hesap oluştur',
      displayName: 'Görünen ad',
      email: 'E-posta',
      password: 'Şifre',
      submit: 'Hesap oluştur',
      haveAccount: 'Zaten hesabınız var mı?',
      login: 'Giriş yap',
      closed: 'Bu realmda kayıt kapalı.',
      success: 'Hesap oluşturuldu. Hoş geldiniz, {name}.',
    },
    error: {
      invalid_credentials: 'E-posta veya şifre yanlış.',
      registration_closed: 'Bu realmda kayıt kapalı.',
      rate_limited: 'Çok fazla deneme. Lütfen bekleyin ve tekrar deneyin.',
      twofa_required: 'Devam etmek için iki faktörlü kodunuzu girin.',
      email_taken: 'Bu e-posta zaten kayıtlı.',
    },
    account: {
      heading: 'Hesap',
      email: 'E-posta',
      displayName: 'Görünen ad',
      memberSince: '{date} tarihinden beri üye',
      logout: 'Çıkış yap',
      loggedOut: 'Çıkış yaptınız.',
      loginPrompt: 'Hesabınızı yönetmek için giriş yapın.',
    },
  },
  armory: {
    heading: 'Cephanelik',
    searchLabel: 'Karakter veya lonca adı',
    searchPlaceholder: 'ör. Aria',
    searchCharacter: 'Karakter bul',
    searchGuild: 'Lonca bul',
    notFound: 'Bu realmda böyle bir karakter veya lonca yok.',
    private: 'Bu realm cephaneliği gizli tutar.',
    character: {
      level: 'Seviye {level} {race} {class}',
      guild: 'Lonca',
      achievements: 'Başarılar',
      itemLevel: 'Öğe seviyesi {value}',
      itemLevelCol: 'ÖS',
      gear: 'Ekipman',
      slot: 'Yuva',
      item: 'Öğe',
      empty: 'Ekipman takılı yok.',
    },
    guild: {
      members: '{count} üye',
      roster: 'Liste',
      member: 'Üye',
      rank: 'Rütbe',
      level: 'Seviye',
    },
  },
  auction: {
    heading: 'Auction evi',
    disabled: 'Bu realmda auction evi kapalı.',
    searchPlaceholder: 'Öğeleri ara…',
    col: { item: 'Öğe', quantity: 'Miktar', buyout: 'Şimdi al', seller: 'Satıcı', time: 'Bitiş' },
    each: 'her biri',
    buy: 'Satın al',
    buying: 'Satın alınıyor…',
    bought: '{item} {price} altına satın alındı.',
    empty: 'Aramanızla eşleşen liste yok.',
    priceHistory: 'Fiyat geçmişi (ortalama şimdi al)',
  },
  feed: {
    heading: 'Dünya akışı',
    disabled: 'Bu realmda dünya akışı kapalı.',
    empty: 'Dünya sessiz… şimdilik.',
    kind: {
      boss_kill: '{actor} {target} yendi.',
      world_boss_spawn: '{target} {zone} bölgesinde uyandı.',
      faction_shift: '{actor} {zone} bölgesinin kontrolünü ele geçirdi.',
      bounty_posted: '{target} üzerine ödül konuldu.',
      milestone: '{target}',
      unknown: 'Dünyada bir şeyler oluyor.',
    },
  },
  downloads: {
    heading: 'İndirilenler',
    body: 'Platformunuz için oyun istemcisini indirin. İndirmenizi sağlanan sağlamalarla doğrulayın.',
    installers: 'Yükleyiciler',
    httpsNote: 'Tüm indirmeler TLS şifrelemesi ile HTTPS üzerinden sunulur.',
    version: 'Sürüm',
    size: 'Boyut',
    download: 'İndir',
    checksum: 'Sağlama',
    requirements: 'Sistem gereksinimleri',
    os: 'İşletim sistemi',
    specs: 'Özellikler',
    verification: 'İndirmenizi doğrulayın',
    verificationBody:
      'İndirdikten sonra, yukarıdaki sağlamayı kullanarak yükleyicinin bütünlüğünü doğrulayın.',
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: 'Çıktıyı yukarıda gösterilen sağlama ile karşılaştırın.',
    backToHome: 'Ana sayfaya dön',
    verifier: {
      heading: 'Sağlama doğrulayıcı',
      label: 'Dosyanızdan sağlamayı girin',
      placeholder: 'Hesapladığınız SHA256 sağlamasını yapıştırın',
      verify: 'Doğrula',
      verifying: 'Doğrulanıyor…',
      match: '✓ Eşleşme — indirmeniz orijinal',
      mismatch: '✗ Eşleşme yok — dosya bozulmuş olabilir',
      invalid: 'Geçersiz sağlama formatı (64 onaltılık karakter bekleniyor)',
      morePlatforms: '+{count} daha fazla platform',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'Intel/AMD CPU, 4GB RAM, 500MB disk',
    osMacos: 'macOS 11+',
    specsMacos: 'Intel/Apple CPU, 4GB RAM, 500MB disk',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'x64 CPU, 4GB RAM, 500MB disk',
  },
  cashShop: {
    heading: 'Mağaza',
    allCategories: 'Tümü',
    buy: 'Satın al',
    buying: 'Satın alınıyor…',
    bought: '{item} {price} kredi için satın alındı.',
    currency: 'krediler',
    col: { item: 'Öğe', category: 'Kategori', price: 'Fiyat' },
    empty: 'Bu kategoride öğe yok.',
    category: {
      boosts: 'Güçlendirmeler',
      cosmetics: 'Kozmetik',
      account: 'Hesap',
      mounts: 'Biniciler',
    },
  },
};
