import type { Catalog } from '@omm/i18n';

export const zh: Catalog = {
  common: {
    loading: '加载中…',
    retry: '重试',
    search: '搜索',
    submit: '提交',
    cancel: '取消',
    close: '关闭',
    empty: '还没有可显示的内容。',
    gold: '{amount} 金币',
  },
  nav: {
    home: '首页',
    play: '游玩',
    downloads: '下载',
    armory: '军械库',
    auction: '拍卖行',
    feed: '世界动态',
    login: '登录',
    register: '创建账户',
    account: '账户',
    logout: '登出',
    skipToContent: '跳转到内容',
  },
  footer: {
    tagline: '开源核心MMORPG引擎。原创IP，MIT许可。',
    poweredBy: '由 Open-MMORPG 驱动',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: '运行在 Open-MMORPG 引擎上的领域。',
    status: {
      heading: '领域状态',
      online: '在线',
      offline: '离线',
      population: '{count} / {capacity} 名冒险者在线',
      loading: '检查领域中…',
      error: '领域状态不可用',
    },
  },
  home: {
    heroCta: '进入领域',
    downloadHeading: '下载客户端',
    downloadBody: '在 Windows、macOS 或 Linux 上游玩。客户端是一个轻量级原生应用。',
    download: '下载',
    featuresHeading: '等待你的内容',
    feature: {
      worldTitle: '一个鲜活的世界',
      worldBody: '服务器权威，水平扩展，始终运行。',
      economyTitle: '真实的经济',
      economyBody: '交易性拍卖行，永不掉线。',
      armoryTitle: '你的传奇，公开',
      armoryBody: '为每个角色和公会提供的一流军械库。',
    },
  },
  errors: {
    network: '无法连接到领域。请检查您的连接并重试。',
    validation: '领域发送了意外内容。这是一个错误 — 请报告它。',
    auth: '您的会话已过期。请重新登录。',
    unknown: '出了点问题。请再试一次。',
  },
  notFound: {
    heading: '在迷雾中迷失',
    body: '此页面在此领域上不存在。',
    home: '返回首页',
  },
  auth: {
    login: {
      heading: '登录',
      email: '电子邮箱',
      password: '密码',
      submit: '登录',
      noAccount: '还没有账户？',
      register: '创建账户',
      success: '欢迎回来，{name}。',
    },
    register: {
      heading: '创建账户',
      displayName: '显示名称',
      email: '电子邮箱',
      password: '密码',
      submit: '创建账户',
      haveAccount: '已有账户？',
      login: '登录',
      closed: '此领域已关闭注册。',
      success: '账户已创建。欢迎，{name}。',
    },
    error: {
      invalid_credentials: '电子邮箱或密码不正确。',
      registration_closed: '此领域已关闭注册。',
      rate_limited: '尝试次数过多。请等待后重试。',
      twofa_required: '输入您的双因素代码以继续。',
      email_taken: '此电子邮箱已被注册。',
    },
    account: {
      heading: '账户',
      email: '电子邮箱',
      displayName: '显示名称',
      memberSince: '{date} 加入',
      logout: '登出',
      loggedOut: '您已登出。',
      loginPrompt: '登录以管理您的账户。',
    },
  },
  armory: {
    heading: '军械库',
    searchLabel: '角色或公会名称',
    searchPlaceholder: '例如：Aria',
    searchCharacter: '查找角色',
    searchGuild: '查找公会',
    notFound: '此领域上没有这样的角色或公会。',
    private: '此领域将军械库设为私密。',
    character: {
      level: '等级 {level} {race} {class}',
      guild: '公会',
      achievements: '成就',
      itemLevel: '物品等级 {value}',
      itemLevelCol: '装等',
      gear: '装备',
      slot: '槽位',
      item: '物品',
      empty: '未装备物品。',
    },
    guild: {
      members: '{count} 名成员',
      roster: '名册',
      member: '成员',
      rank: '等级',
      level: '等级',
    },
  },
  auction: {
    heading: '拍卖行',
    disabled: '此领域的拍卖行已关闭。',
    searchPlaceholder: '搜索物品…',
    col: { item: '物品', quantity: '数量', buyout: '一口价', seller: '卖家', time: '结束' },
    each: '每个',
    buy: '购买',
    buying: '购买中…',
    bought: '以 {price} 金币购买了 {item}。',
    empty: '没有符合您搜索的拍卖。',
    priceHistory: '价格历史（平均一口价）',
  },
  feed: {
    heading: '世界动态',
    disabled: '此领域的世界动态已关闭。',
    empty: '世界很安静… 暂时。',
    kind: {
      boss_kill: '{actor} 击败了 {target}。',
      world_boss_spawn: '{target} 在 {zone} 觉醒。',
      faction_shift: '{actor} 接管了 {zone} 的控制权。',
      bounty_posted: '对 {target} 发布了赏金。',
      milestone: '{target}',
      unknown: '世界中有一些骚动。',
    },
  },
  downloads: {
    heading: '下载',
    body: '下载您平台的游戏客户端。使用提供的校验和验证您的下载。',
    installers: '安装程序',
    httpsNote: '所有下载均通过 HTTPS 和 TLS 加密提供。',
    version: '版本',
    size: '大小',
    download: '下载',
    checksum: '校验和',
    requirements: '系统要求',
    os: '操作系统',
    specs: '规格',
    verification: '验证您的下载',
    verificationBody: '下载后，使用上面的校验和验证安装程序的完整性。',
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: '将输出与上面显示的校验和进行比较。',
    backToHome: '返回首页',
    verifier: {
      heading: '校验和验证器',
      label: '输入您文件的校验和',
      placeholder: '粘贴您计算的 SHA256 校验和',
      verify: '验证',
      verifying: '验证中…',
      match: '✓ 匹配 — 您的下载是真实的',
      mismatch: '✗ 不匹配 — 文件可能已损坏',
      invalid: '无效的校验和格式（需要 64 个十六进制字符）',
      morePlatforms: '+{count} 个更多平台',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'Intel/AMD CPU，4GB 内存，500MB 磁盘',
    osMacos: 'macOS 11+',
    specsMacos: 'Intel/Apple CPU，4GB 内存，500MB 磁盘',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'x64 CPU，4GB 内存，500MB 磁盘',
  },
  cashShop: {
    heading: '商城',
    allCategories: '全部',
    buy: '购买',
    buying: '购买中…',
    bought: '以 {price} 积分购买了 {item}。',
    currency: '积分',
    col: {
      item: '物品',
      category: '分类',
      price: '价格',
    },
    empty: '此分类中没有物品。',
    category: {
      boosts: '增益',
      cosmetics: '外观',
      account: '账户',
      mounts: '坐骑',
    },
  },
};
