import type { Catalog } from '@omm/i18n';

export const ru: Catalog = {
  common: {
    loading: 'Загрузка…',
    retry: 'Повторить',
    search: 'Поиск',
    submit: 'Отправить',
    cancel: 'Отмена',
    close: 'Закрыть',
    empty: 'Пока ничего нет.',
    gold: '{amount} золота',
  },
  nav: {
    home: 'Главная',
    play: 'Играть',
    downloads: 'Загрузки',
    armory: 'Оружейная',
    auction: 'Аукционный дом',
    feed: 'Мировая лента',
    login: 'Войти',
    register: 'Создать аккаунт',
    account: 'Аккаунт',
    logout: 'Выйти',
    skipToContent: 'Перейти к содержимому',
  },
  footer: {
    tagline: 'Движок MMORPG с открытым ядром. Оригинальный IP, лицензия MIT.',
    poweredBy: 'Работает на Open-MMORPG',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'Царство, работающее на движке Open-MMORPG.',
    status: {
      heading: 'Статус царства',
      online: 'В сети',
      offline: 'Не в сети',
      population: '{count} / {capacity} приключенцев в сети',
      loading: 'Проверка царства…',
      error: 'Статус царства недоступен',
    },
  },
  home: {
    heroCta: 'Войти в царство',
    downloadHeading: 'Скачать клиент',
    downloadBody: 'Играйте на Windows, macOS или Linux. Клиент — это легкое нативное приложение.',
    download: 'Скачать',
    featuresHeading: 'Что вас ждет',
    feature: {
      worldTitle: 'Живой мир',
      worldBody: 'Авторитарный сервер, горизонтальное масштабирование, всегда жив.',
      economyTitle: 'Настоящая экономика',
      economyBody: 'Транзакционный аукционный дом, без дюпов, никогда.',
      armoryTitle: 'Ваша легенда, публичная',
      armoryBody: 'Оружейная первого класса для каждого персонажа и гильдии.',
    },
  },
  errors: {
    network: 'Не удается связаться с царством. Проверьте подключение и повторите попытку.',
    validation: 'Царство отправило что-то неожиданное. Это ошибка — пожалуйста, сообщите об этом.',
    auth: 'Ваша сессия истекла. Пожалуйста, войдите снова.',
    unknown: 'Что-то пошло не так. Пожалуйста, попробуйте еще раз.',
  },
  notFound: {
    heading: 'Потерян в тумане',
    body: 'Эта страница не существует в этом царстве.',
    home: 'Вернуться на главную',
  },
  auth: {
    login: {
      heading: 'Войти',
      email: 'Электронная почта',
      password: 'Пароль',
      submit: 'Войти',
      noAccount: 'Еще нет аккаунта?',
      register: 'Создать аккаунт',
      success: 'Добро пожаловать, {name}.',
    },
    register: {
      heading: 'Создать аккаунт',
      displayName: 'Отображаемое имя',
      email: 'Электронная почта',
      password: 'Пароль',
      submit: 'Создать аккаунт',
      haveAccount: 'Уже есть аккаунт?',
      login: 'Войти',
      closed: 'Регистрация закрыта в этом царстве.',
      success: 'Аккаунт создан. Добро пожаловать, {name}.',
    },
    error: {
      invalid_credentials: 'Электронная почта или пароль неверны.',
      registration_closed: 'Регистрация закрыта в этом царстве.',
      rate_limited: 'Слишком много попыток. Подождите и попробуйте снова.',
      twofa_required: 'Введите код двухфакторной аутентификации для продолжения.',
      email_taken: 'Эта электронная почта уже зарегистрирована.',
    },
    account: {
      heading: 'Аккаунт',
      email: 'Электронная почта',
      displayName: 'Отображаемое имя',
      memberSince: 'Участник с {date}',
      logout: 'Выйти',
      loggedOut: 'Вы вышли.',
      loginPrompt: 'Войдите, чтобы управлять аккаунтом.',
    },
  },
  armory: {
    heading: 'Оружейная',
    searchLabel: 'Имя персонажа или гильдии',
    searchPlaceholder: 'напр. Ария',
    searchCharacter: 'Найти персонажа',
    searchGuild: 'Найти гильдию',
    notFound: 'Такой персонаж или гильдия не существует в этом царстве.',
    private: 'Это царство делает оружейную частной.',
    character: {
      level: 'Уровень {level} {race} {class}',
      guild: 'Гильдия',
      achievements: 'Достижения',
      itemLevel: 'Уровень предмета {value}',
      itemLevelCol: 'Ур',
      gear: 'Снаряжение',
      slot: 'Ячейка',
      item: 'Предмет',
      empty: 'Снаряжение не надето.',
    },
    guild: {
      members: '{count} участников',
      roster: 'Список',
      member: 'Участник',
      rank: 'Ранг',
      level: 'Уровень',
    },
  },
  auction: {
    heading: 'Аукционный дом',
    disabled: 'Аукционный дом закрыт в этом царстве.',
    searchPlaceholder: 'Поиск предметов…',
    col: {
      item: 'Предмет',
      quantity: 'Кол-во',
      buyout: 'Выкуп',
      seller: 'Продавец',
      time: 'Завершение',
    },
    each: 'шт',
    buy: 'Купить',
    buying: 'Покупка…',
    bought: '{item} куплен за {price} золота.',
    empty: 'Нет лотов, соответствующих поиску.',
    priceHistory: 'История цен (средний выкуп)',
  },
  feed: {
    heading: 'Мировая лента',
    disabled: 'Мировая лента отключена в этом царстве.',
    empty: 'Мир тих… пока.',
    kind: {
      boss_kill: '{actor} победил {target}.',
      world_boss_spawn: '{target} пробудился в {zone}.',
      faction_shift: '{actor} захватил контроль над {zone}.',
      bounty_posted: 'Была размещена награда на {target}.',
      milestone: '{target}',
      unknown: 'Что-то происходит в мире.',
    },
  },
  downloads: {
    heading: 'Загрузки',
    body: 'Загрузите игровой клиент для вашей платформы. Проверьте загрузку с помощью контрольных сумм.',
    installers: 'Установщики',
    httpsNote: 'Все загрузки осуществляются через HTTPS с TLS-шифрованием.',
    version: 'Версия',
    size: 'Размер',
    download: 'Скачать',
    checksum: 'Контрольная сумма',
    requirements: 'Системные требования',
    os: 'Операционная система',
    specs: 'Характеристики',
    verification: 'Проверить загрузку',
    verificationBody:
      'После загрузки проверьте целостность установщика с помощью контрольной суммы выше.',
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: 'Сравните вывод с контрольной суммой выше.',
    backToHome: 'Вернуться на главную',
    verifier: {
      heading: 'Проверка контрольной суммы',
      label: 'Введите контрольную сумму из вашего файла',
      placeholder: 'Вставьте вычисленную контрольную сумму SHA256',
      verify: 'Проверить',
      verifying: 'Проверка…',
      match: '✓ Совпадение — ваша загрузка подлинная',
      mismatch: '✗ Несовпадение — файл может быть поврежден',
      invalid: 'Недопустимый формат контрольной суммы (ожидается 64 шестнадцатеричных символа)',
      morePlatforms: '+{count} еще платформ',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'Процессор Intel/AMD, 4ГБ ОЗУ, 500МБ диск',
    osMacos: 'macOS 11+',
    specsMacos: 'Процессор Intel/Apple, 4ГБ ОЗУ, 500МБ диск',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'Процессор x64, 4ГБ ОЗУ, 500МБ диск',
  },
  cashShop: {
    heading: 'Магазин',
    allCategories: 'Все',
    buy: 'Купить',
    buying: 'Покупка…',
    bought: '{item} куплен за {price} кредитов.',
    currency: 'кредиты',
    col: {
      item: 'Предмет',
      category: 'Категория',
      price: 'Цена',
    },
    empty: 'В этой категории нет предметов.',
    category: {
      boosts: 'Усиления',
      cosmetics: 'Косметика',
      account: 'Аккаунт',
      mounts: 'Маунты',
    },
  },
};
