import type { Catalog } from '@omm/i18n';

export const ar: Catalog = {
  common: {
    loading: 'جاري التحميل…',
    retry: 'إعادة المحاولة',
    search: 'بحث',
    submit: 'إرسال',
    cancel: 'إلغاء',
    close: 'إغلاق',
    empty: 'لا شيء لعرضه بعد.',
    gold: '{amount} ذهب',
  },
  nav: {
    home: 'الرئيسية',
    play: 'العب',
    downloads: 'التنزيلات',
    armory: 'مخزن الأسلحة',
    auction: 'بيت المزاد',
    feed: 'تغذية العالم',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    account: 'الحساب',
    logout: 'تسجيل الخروج',
    skipToContent: 'انتقل إلى المحتوى',
  },
  footer: {
    tagline:
      'محرك ألعاب تقمص أدوار متعددة اللاعبين عبر الإنترنت ذات نواة مفتوحة. الملكية الفكرية الأصلية، مرخص تحت MIT.',
    poweredBy: 'مدعوم بواسطة Open-MMORPG',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'مملكة تعمل على محرك Open-MMORPG.',
    status: {
      heading: 'حالة المملكة',
      online: 'متصل',
      offline: 'غير متصل',
      population: '{count} / {capacity} مغامرين متصلين',
      loading: 'التحقق من المملكة…',
      error: 'حالة المملكة غير متاحة',
    },
  },
  home: {
    heroCta: 'أدخل المملكة',
    downloadHeading: 'تنزيل العميل',
    downloadBody: 'العب على Windows أو macOS أو Linux. العميل هو تطبيق أصلي خفيف.',
    download: 'تنزيل',
    featuresHeading: 'ما ينتظرك',
    feature: {
      worldTitle: 'عالم حي',
      worldBody: 'بتوجيه من الخادم، قابل للتوسع أفقيًا، حي دائمًا.',
      economyTitle: 'اقتصاد حقيقي',
      economyBody: 'بيت مزاد معامل بدون نسخ مكررة، أبدًا.',
      armoryTitle: 'أسطورتك، علنية',
      armoryBody: 'مخزن أسلحة من الدرجة الأولى لكل شخصية ونجل.',
    },
  },
  errors: {
    network: 'لا يمكن الوصول إلى المملكة. تحقق من اتصالك وحاول مرة أخرى.',
    validation: 'أرسلت المملكة شيئًا غير متوقع. هذا خطأ — يرجى الإبلاغ عنه.',
    auth: 'انتهت جلستك. يرجى تسجيل الدخول مرة أخرى.',
    unknown: 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
  },
  notFound: {
    heading: 'ضائع في الضباب',
    body: 'هذه الصفحة غير موجودة في هذه المملكة.',
    home: 'العودة إلى الرئيسية',
  },
  auth: {
    login: {
      heading: 'تسجيل الدخول',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      submit: 'تسجيل الدخول',
      noAccount: 'ليس لديك حساب بعد؟',
      register: 'إنشاء حساب',
      success: 'مرحبًا بعودتك، {name}.',
    },
    register: {
      heading: 'إنشاء حساب',
      displayName: 'اسم العرض',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      submit: 'إنشاء حساب',
      haveAccount: 'لديك حساب بالفعل؟',
      login: 'تسجيل الدخول',
      closed: 'التس مغلق في هذه المملكة.',
      success: 'تم إنشاء الحساب. مرحبًا، {name}.',
    },
    error: {
      invalid_credentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      registration_closed: 'التسجيل مغلق في هذه المملكة.',
      rate_limited: 'محاولات كثيرة جدًا. يرجى الانتظار والمحاولة مرة أخرى.',
      twofa_required: 'أدخل رمز المصادقة الثنائية للمتابعة.',
      email_taken: 'هذا البريد الإلكتروني مسجل بالفعل.',
      wrong_password: 'كلمة المرور الحالية غير صحيحة.',
      password_too_short: 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل.',
      password_mismatch: 'كلمتا المرور الجديدتان غير متطابقتين.',
    },
    account: {
      heading: 'الحساب',
      email: 'البريد الإلكتروني',
      displayName: 'اسم العرض',
      memberSince: 'عضو منذ {date}',
      logout: 'تسجيل الخروج',
      loggedOut: 'لقد قمت بتسجيل الخروج.',
      loginPrompt: 'سجل الدخول لإدارة حسابك.',
      settings: {
        heading: 'إعدادات الحساب',
        profileHeading: 'الملف الشخصي',
        saveProfile: 'حفظ الملف الشخصي',
        profileSaved: 'تم حفظ الملف الشخصي.',
        passwordHeading: 'تغيير كلمة المرور',
        currentPassword: 'كلمة المرور الحالية',
        newPassword: 'كلمة المرور الجديدة',
        confirmPassword: 'تأكيد كلمة المرور الجديدة',
        changePassword: 'تغيير كلمة المرور',
        passwordChanged: 'تم تغيير كلمة المرور.',
      },
    },
  },
  armory: {
    heading: 'مخزن الأسلحة',
    searchLabel: 'اسم الشخصية أو النجل',
    searchPlaceholder: 'مثال: Aria',
    searchCharacter: 'البحث عن شخصية',
    searchGuild: 'البحث عن نجل',
    notFound: 'لا توجد شخصية أو نجل من هذا القبيل في هذه المملكة.',
    private: 'هذه المملكة تحتفظ بمخزن الأسلحة خاصًا.',
    character: {
      level: 'مستوى {level} {race} {class}',
      guild: 'نجل',
      achievements: 'الإنجازات',
      itemLevel: 'مستوى العنصر {value}',
      itemLevelCol: 'م ع',
      gear: 'المعدات',
      slot: 'الفتحة',
      item: 'العنصر',
      empty: 'لا توجد معدات مجهزة.',
    },
    guild: {
      members: '{count} أعضاء',
      roster: 'القائمة',
      member: 'العضو',
      rank: 'الرتبة',
      level: 'المستوى',
    },
  },
  auction: {
    heading: 'بيت المزاد',
    disabled: 'بيت المزاد مغلق في هذه المملكة.',
    searchPlaceholder: 'البحث عن العناصر…',
    col: {
      item: 'العنصر',
      quantity: 'الكمية',
      buyout: 'الشراء الفوري',
      seller: 'البائع',
      time: 'النهاية',
    },
    each: 'كل',
    buy: 'شراء',
    buying: 'جاري الشراء…',
    bought: 'تم شراء {item} مقابل {price} ذهب.',
    empty: 'لا توجد قوائم تطابق بحثك.',
    priceHistory: 'سجل السعر (متوسط الشراء الفوري)',
  },
  feed: {
    heading: 'تغذية العالم',
    disabled: 'تغذية العالم مغفلة في هذه المملكة.',
    empty: 'العالم هادئ… في الوقت الحالي.',
    kind: {
      boss_kill: 'قام {actor} بهزيمة {target}.',
      world_boss_spawn: 'استيقظ {target} في {zone}.',
      faction_shift: 'سيطر {actor} على {zone}.',
      bounty_posted: 'تم وضع مكافأة على {target}.',
      milestone: '{target}',
      unknown: 'شيء يتحرك في العالم.',
    },
  },
  downloads: {
    heading: 'التنزيلات',
    body: 'قم بتنزيل عميل اللعب لمنصتك. تحقق من التنزيل الخاص بك باستخدام المجموعات الاختبارية المقدمة.',
    installers: 'برامج التثبيت',
    httpsNote: 'جميع التنزيلات تقدم عبر HTTPS مع تشفير TLS.',
    version: 'الإصدار',
    size: 'الحجم',
    download: 'تنزيل',
    checksum: 'المجموع الاختباري',
    requirements: 'متطلبات النظام',
    os: 'نظام التشغيل',
    specs: 'المواصفات',
    verification: 'التحقق من التنزيل',
    verificationBody: 'بعد التنزيل، تحقق من سلامة برنامج التثبيت باستخدام المجموع الاختباري أعلاه.',
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: 'قارن المخرجات مع المجموع الاختباري المعروض أعلاه.',
    backToHome: 'العودة إلى الرئيسية',
    verifier: {
      heading: 'مدقق المجموع الاختباري',
      label: 'أدخل المجموع الاختباري من ملفك',
      placeholder: 'الصق المجموع الاختباري SHA256 الذي حسابته',
      verify: 'تحقق',
      verifying: 'جاري التحقق…',
      match: '✓ تطابق — تنزيلك أصلي',
      mismatch: '✗ عدم تطابق — قد يكون الملف تالفًا',
      invalid: 'تنسيق مجموع اختباري غير صالح (64 حرفًا سداسيًا عشريًا متوقعًا)',
      morePlatforms: '+{count} منصات إضافية',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'وحدة معالجة Intel/AMD، 4 جيجابايت رام، 500 ميجابايت قرص',
    osMacos: 'macOS 11+',
    specsMacos: 'وحدة معالجة Intel/Apple، 4 جيجابايت رام، 500 ميجابايت قرص',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'وحدة معالجة x64، 4 جيجابايت رام، 500 ميجابايت قرص',
  },
  cashShop: {
    heading: 'المتجر',
    allCategories: 'الكل',
    buy: 'شراء',
    buying: 'جاري الشراء…',
    bought: 'تم شراء {item} مقابل {price} ائتمان.',
    currency: 'ائتمانات',
    col: {
      item: 'العنصر',
      category: 'الفئة',
      price: 'السعر',
    },
    empty: 'لا توجد عناصر في هذه الفئة.',
    category: {
      boosts: 'التعزيزات',
      cosmetics: 'التجميليات',
      account: 'الحساب',
      mounts: 'المراكب',
    },
  },
};
