import type { Catalog } from '@omm/i18n';

export const pl: Catalog = {
  common: {
    loading: 'Ładowanie…',
    retry: 'Ponów',
    search: 'Szukaj',
    submit: 'Wyślij',
    cancel: 'Anuluj',
    close: 'Zamknij',
    empty: 'Nic jeszcze do pokazania.',
    gold: '{amount} złota',
  },
  nav: {
    home: 'Strona główna',
    play: 'Graj',
    downloads: 'Pobieranie',
    armory: 'Zbrojownia',
    auction: 'Dom aukcyjny',
    feed: 'Kanał świata',
    login: 'Zaloguj',
    register: 'Utwórz konto',
    account: 'Konto',
    logout: 'Wyloguj',
    skipToContent: 'Przejdź do treści',
  },
  footer: {
    tagline: 'Silnik MMORPG o otwartym rdzeniu. Oryginalna IP, licencjonowane przez MIT.',
    poweredBy: 'Obsługiwane przez Open-MMORPG',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'Królestwo działające na silniku Open-MMORPG.',
    status: {
      heading: 'Status królestwa',
      online: 'Online',
      offline: 'Offline',
      population: '{count} / {capacity} poszukiwaczy online',
      loading: 'Sprawdzanie królestwa…',
      error: 'Status królestwa niedostępny',
    },
  },
  home: {
    heroCta: 'Wejdź do królestwa',
    downloadHeading: 'Pobierz klienta',
    downloadBody: 'Graj na Windows, macOS lub Linux. Klient to lekka aplikacja natywna.',
    download: 'Pobierz',
    featuresHeading: 'Ciebie czeka',
    feature: {
      worldTitle: 'Żyjący świat',
      worldBody: 'Autorytatywny serwer, skalowalność pozioma, zawsze żywy.',
      economyTitle: 'Prawdziwa ekonomia',
      economyBody: 'Transakcyjny dom aukcyjny bez duplikatów, nigdy.',
      armoryTitle: 'Twoja legenda, publiczna',
      armoryBody: 'Zbrojownia pierwszej klasy dla każdej postaci i gildii.',
    },
  },
  errors: {
    network: 'Nie można połączyć się z królestwem. Sprawdź połączenie i spróbuj ponownie.',
    validation: 'Królestwo wysłało coś nieoczekiwanego. To jest błąd — proszę zgłoś to.',
    auth: 'Twoja sesja wygasła. Proszę zaloguj się ponownie.',
    unknown: 'Coś poszło nie tak. Proszę spróbuj ponownie.',
  },
  notFound: {
    heading: 'Zagubiony w mgłach',
    body: 'Ta strona nie istnieje w tym królestwie.',
    home: 'Powrót do strony głównej',
  },
  auth: {
    login: {
      heading: 'Zaloguj',
      email: 'E-mail',
      password: 'Hasło',
      submit: 'Zaloguj',
      noAccount: 'Nie masz jeszcze konta?',
      register: 'Utwórz konto',
      success: 'Witaj ponownie, {name}.',
    },
    register: {
      heading: 'Utwórz konto',
      displayName: 'Wyświetlana nazwa',
      email: 'E-mail',
      password: 'Hasło',
      submit: 'Utwórz konto',
      haveAccount: 'Masz już konto?',
      login: 'Zaloguj',
      closed: 'Rejestracja jest zamknięta w tym królestwie.',
      success: 'Konto utworzone. Witaj, {name}.',
    },
    error: {
      invalid_credentials: 'E-mail lub hasło jest nieprawidłowe.',
      registration_closed: 'Rejestracja jest zamknięta w tym królestwie.',
      rate_limited: 'Zbyt wiele prób. Proszę czekać i spróbować ponownie.',
      twofa_required: 'Wprowadź kod dwuskładnikowy, aby kontynuować.',
      email_taken: 'Ten e-mail jest już zarejestrowany.',
      wrong_password: 'Twoje obecne hasło jest nieprawidłowe.',
      password_too_short: 'Hasło musi mieć co najmniej 8 znaków.',
      password_mismatch: 'Nowe hasła nie są zgodne.',
    },
    account: {
      heading: 'Konto',
      email: 'E-mail',
      displayName: 'Wyświetlana nazwa',
      memberSince: 'Cłonek od {date}',
      logout: 'Wyloguj',
      loggedOut: 'Jesteś wylogowany.',
      loginPrompt: 'Zaloguj się, aby zarządzać swoim kontem.',
      settings: {
        heading: 'Ustawienia konta',
        profileHeading: 'Profil',
        saveProfile: 'Zapisz profil',
        profileSaved: 'Profil zapisany.',
        passwordHeading: 'Zmień hasło',
        currentPassword: 'Obecne hasło',
        newPassword: 'Nowe hasło',
        confirmPassword: 'Potwierdź nowe hasło',
        changePassword: 'Zmień hasło',
        passwordChanged: 'Hasło zmienione.',
      },
    },
  },
  armory: {
    heading: 'Zbrojownia',
    searchLabel: 'Nazwa postaci lub gildii',
    searchPlaceholder: 'np. Aria',
    searchCharacter: 'Znajdź postać',
    searchGuild: 'Znajdź gildię',
    notFound: 'Brak takiej postaci lub gildii w tym królestwie.',
    private: 'To królestwo utrzymuje zbrojownię prywatną.',
    character: {
      level: 'Poziom {level} {race} {class}',
      guild: 'Gildia',
      achievements: 'Osiągnięcia',
      itemLevel: 'Poziom przedmiotu {value}',
      itemLevelCol: 'PP',
      gear: 'Ekwipunek',
      slot: 'Slot',
      item: 'Przedmiot',
      empty: 'Brak wyposażonego ekwipunku.',
    },
    guild: {
      members: '{count} członków',
      roster: 'Lista',
      member: 'Członek',
      rank: 'Ranga',
      level: 'Poziom',
    },
  },
  auction: {
    heading: 'Dom aukcyjny',
    disabled: 'Dom aukcyjny jest zamknięty w tym królestwie.',
    searchPlaceholder: 'Szukaj przedmiotów…',
    col: {
      item: 'Przedmiot',
      quantity: 'Ilość',
      buyout: 'Kup teraz',
      seller: 'Sprzedawca',
      time: 'Koniec',
    },
    each: 'szt.',
    buy: 'Kup',
    buying: 'Kupowanie…',
    bought: '{item} kupiony za {price} złota.',
    empty: 'Brak ofert pasujących do wyszukiwania.',
    priceHistory: 'Historia cen (średnia kup teraz)',
  },
  feed: {
    heading: 'Kanał świata',
    disabled: 'Kanał świata jest wyłączony w tym królestwie.',
    empty: 'Świat jest cichy… na razie.',
    kind: {
      boss_kill: '{actor} pokonał {target}.',
      world_boss_spawn: '{target} obudził się w {zone}.',
      faction_shift: '{actor} przejął kontrolę nad {zone}.',
      bounty_posted: 'Nagroda została postawiona na {target}.',
      milestone: '{target}',
      unknown: 'Coś dzieje się w świecie.',
    },
  },
  downloads: {
    heading: 'Pobieranie',
    body: 'Pobierz klienta gry dla swojej platformy. Zweryfikuj pobieranie za pomocą dostarczonych sum kontrolnych.',
    installers: 'Instalatory',
    httpsNote: 'Wszystkie pobrania są obsługiwane przez HTTPS z szyfrowaniem TLS.',
    version: 'Wersja',
    size: 'Rozmiar',
    download: 'Pobierz',
    checksum: 'Suma kontrolna',
    requirements: 'Wymagania systemowe',
    os: 'System operacyjny',
    specs: 'Specyfikacje',
    verification: 'Zweryfikuj pobieranie',
    verificationBody:
      'Po pobraniu zweryfikuj integralność instalatora używając sumy kontrolnej powyżej.',
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: 'Porównaj wynik z sumą kontrolną pokazaną powyżej.',
    backToHome: 'Powrót do strony głównej',
    verifier: {
      heading: 'Weryfikator sumy kontrolnej',
      label: 'Wprowadź sumę kontrolną z pliku',
      placeholder: 'Wklej obliczoną sumę kontrolną SHA256',
      verify: 'Zweryfikuj',
      verifying: 'Weryfikacja…',
      match: '✓ Dopasowanie — twoje pobieranie jest autentyczne',
      mismatch: '✗ Brak dopasowania — plik może być uszkodzony',
      invalid: 'Nieprawidłowy format sumy kontrolnej (oczekiwano 64 znaków szesnastkowych)',
      morePlatforms: '+{count} więcej platform',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'CPU Intel/AMD, 4GB RAM, 500MB dysk',
    osMacos: 'macOS 11+',
    specsMacos: 'CPU Intel/Apple, 4GB RAM, 500MB dysk',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'CPU x64, 4GB RAM, 500MB dysk',
  },
  cashShop: {
    heading: 'Sklep',
    allCategories: 'Wszystkie',
    buy: 'Kup',
    buying: 'Kupowanie…',
    bought: '{item} kupiony za {price} kredytów.',
    currency: 'kredyty',
    col: { item: 'Przedmiot', category: 'Kategoria', price: 'Cena' },
    empty: 'Brak przedmiotów w tej kategorii.',
    category: {
      boosts: 'Wzmocnienia',
      cosmetics: 'Kosmetyki',
      account: 'Konto',
      mounts: 'Wierzchowce',
    },
  },
};
