import type { Catalog } from '@omm/i18n';

export const it: Catalog = {
  common: {
    loading: 'Caricamento…',
    retry: 'Riprova',
    search: 'Cerca',
    submit: 'Invia',
    cancel: 'Annulla',
    close: 'Chiudi',
    empty: 'Nulla da mostrare ancora.',
    gold: '{amount} oro',
  },
  nav: {
    home: 'Home',
    play: 'Gioca',
    downloads: 'Download',
    armory: 'Arsenale',
    auction: "Casa d'asta",
    feed: 'Feed del mondo',
    login: 'Accedi',
    register: 'Crea account',
    account: 'Account',
    logout: 'Esci',
    skipToContent: 'Salta al contenuto',
  },
  footer: {
    tagline: 'Un motore MMORPG open-core. IP originale, con licenza MIT.',
    poweredBy: 'Alimentato da Open-MMORPG',
    rights: '© {year} {name}',
  },
  realm: {
    title: '{name}',
    tagline: 'Un reame che funziona sul motore Open-MMORPG.',
    status: {
      heading: 'Stato del reame',
      online: 'Online',
      offline: 'Offline',
      population: '{count} / {capacity} avventurieri online',
      loading: 'Controllo reame…',
      error: 'Stato del reame non disponibile',
    },
  },
  home: {
    heroCta: 'Entra nel reame',
    downloadHeading: 'Scarica il client',
    downloadBody: "Gioca su Windows, macOS o Linux. Il client è un'app nativa leggera.",
    download: 'Scarica',
    featuresHeading: 'Cosa ti aspetta',
    feature: {
      worldTitle: 'Un mondo vivo',
      worldBody: 'Autoritativo dal server, scalato orizzontalmente, sempre vivo.',
      economyTitle: "Un'economia reale",
      economyBody: "Una casa d'asta transazionale senza duplicati, mai.",
      armoryTitle: 'La tua leggenda, pubblica',
      armoryBody: 'Un arsenale di prima classe per ogni personaggio e gilda.',
    },
  },
  errors: {
    network: 'Impossibile raggiungere il reame. Controlla la tua connessione e riprova.',
    validation: 'Il reame ha inviato qualcosa di inatteso. Questo è un bug — per favore, segnala.',
    auth: 'La tua sessione è scaduta. Per favore, accedi di nuovo.',
    unknown: 'Qualcosa è andato storto. Per favore, riprova.',
  },
  notFound: {
    heading: 'Perso nelle nebbie',
    body: 'Questa pagina non esiste in questo reame.',
    home: 'Torna alla home',
  },
  auth: {
    login: {
      heading: 'Accedi',
      email: 'Email',
      password: 'Password',
      submit: 'Accedi',
      noAccount: 'Non hai ancora un account?',
      register: 'Crea un account',
      success: 'Bentornato, {name}.',
    },
    register: {
      heading: 'Crea account',
      displayName: 'Nome visualizzato',
      email: 'Email',
      password: 'Password',
      submit: 'Crea account',
      haveAccount: 'Hai già un account?',
      login: 'Accedi',
      closed: 'La registrazione è chiusa in questo reame.',
      success: 'Account creato. Benvenuto, {name}.',
    },
    error: {
      invalid_credentials: 'Email o password non corretti.',
      registration_closed: 'La registrazione è chiusa in questo reame.',
      rate_limited: 'Troppi tentativi. Per favore, attendi e riprova.',
      twofa_required: 'Inserisci il codice a due fattori per continuare.',
      email_taken: 'Questa email è già registrata.',
    },
    account: {
      heading: 'Account',
      email: 'Email',
      displayName: 'Nome visualizzato',
      memberSince: 'Membro dal {date}',
      logout: 'Esci',
      loggedOut: 'Sei disconnesso.',
      loginPrompt: 'Accedi per gestire il tuo account.',
    },
  },
  armory: {
    heading: 'Arsenale',
    searchLabel: 'Nome personaggio o gilda',
    searchPlaceholder: 'es. Aria',
    searchCharacter: 'Trova personaggio',
    searchGuild: 'Trova gilda',
    notFound: 'Nessun personaggio o gilda simile in questo reame.',
    private: "Questo reame mantiene l'arsenale privato.",
    character: {
      level: 'Livello {level} {race} {class}',
      guild: 'Gilda',
      achievements: 'Achievement',
      itemLevel: 'Livello oggetto {value}',
      itemLevelCol: 'Liv',
      gear: 'Equipaggiamento',
      slot: 'Slot',
      item: 'Oggetto',
      empty: 'Nessun equipaggiamento equipaggiato.',
    },
    guild: {
      members: '{count} membri',
      roster: 'Roster',
      member: 'Membro',
      rank: 'Rango',
      level: 'Livello',
    },
  },
  auction: {
    heading: "Casa d'asta",
    disabled: "La casa d'asta è chiusa in questo reame.",
    searchPlaceholder: 'Cerca oggetti…',
    col: {
      item: 'Oggetto',
      quantity: 'Qta',
      buyout: 'Compra ora',
      seller: 'Venditore',
      time: 'Fine',
    },
    each: 'cad',
    buy: 'Comprare',
    buying: 'Acquisto…',
    bought: '{item} acquistato per {price} oro.',
    empty: 'Nessuna offerta corrisponde alla tua ricerca.',
    priceHistory: 'Storico prezzi (media compra ora)',
  },
  feed: {
    heading: 'Feed del mondo',
    disabled: 'Il feed del mondo è spento in questo reame.',
    empty: 'Il mondo è tranquillo… per ora.',
    kind: {
      boss_kill: '{actor} ha sconfitto {target}.',
      world_boss_spawn: '{target} si è svegliato in {zone}.',
      faction_shift: '{actor} ha preso il controllo di {zone}.',
      bounty_posted: 'È stata posta una taglia su {target}.',
      milestone: '{target}',
      unknown: 'Qualcosa si agita nel mondo.',
    },
  },
  downloads: {
    heading: 'Download',
    body: 'Scarica il client di gioco per la tua piattaforma. Verifica il tuo download con i checksum forniti.',
    installers: 'Installer',
    httpsNote: 'Tutti i download sono serviti tramite HTTPS con crittografia TLS.',
    version: 'Versione',
    size: 'Dimensione',
    download: 'Scarica',
    checksum: 'Checksum',
    requirements: 'Requisiti di sistema',
    os: 'Sistema operativo',
    specs: 'Specifiche',
    verification: 'Verifica il tuo download',
    verificationBody:
      "Dopo il download, verifica l'integrità dell'installer usando il checksum sopra.",
    filenameExample: 'open-mmorpg-0.1.0-windows-x64.exe',
    verificationHint: "Confronta l'output con il checksum mostrato sopra.",
    backToHome: 'Torna alla home',
    verifier: {
      heading: 'Verificatore checksum',
      label: 'Inserisci il checksum dal tuo file',
      placeholder: 'Incolla il checksum SHA256 che hai calcolato',
      verify: 'Verifica',
      verifying: 'Verifica…',
      match: '✓ Corrispondenza — il tuo download è autentico',
      mismatch: '✗ Nessuna corrispondenza — il file potrebbe essere danneggiato',
      invalid: 'Formato checksum non valido (previsti 64 caratteri esadecimali)',
      morePlatforms: '+{count} più piattaforme',
    },
    osWindows: 'Windows 10+',
    specsWindows: 'CPU Intel/AMD, 4GB RAM, 500MB disco',
    osMacos: 'macOS 11+',
    specsMacos: 'CPU Intel/Apple, 4GB RAM, 500MB disco',
    osLinux: 'Linux (Ubuntu 20.04+)',
    specsLinux: 'CPU x64, 4GB RAM, 500MB disco',
  },
  cashShop: {
    heading: 'Negozio',
    allCategories: 'Tutte',
    buy: 'Comprare',
    buying: 'Acquisto…',
    bought: '{item} acquistato per {price} crediti.',
    currency: 'crediti',
    col: { item: 'Oggetto', category: 'Categoria', price: 'Prezzo' },
    empty: 'Nessun oggetto in questa categoria.',
    category: {
      boosts: 'Boost',
      cosmetics: 'Cosmetici',
      account: 'Account',
      mounts: 'Cavalcature',
    },
  },
};
